# 데이터 불러오기

In [1]:
import os
import pickle
import pandas as pd

In [2]:
file_path = './total_merged_data_1108_2.txt'

In [3]:
pd.set_option('display.max_columns', None)  
pd.set_option('display.max_rows', 50)
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

In [4]:
with open(file_path, 'rb') as f:
    temp = pickle.load(f)

In [5]:
temp

         deal_price  deal_year  deal_month full_loc_code loc_code_x gu_list law_code dong   ji_bun         apt_name_y    area  current_floor  build_y  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineIC  S-LineAir  distance    avg_price              full_addr              apt_jibun  cont_rank  com_year com_mon  bldg_age  lv_fg
0        29500       2006       1           1111019       11110      종로구     당주동      19   100      세종                 93.40   6              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     315.845824   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      23        4.0
1        28000       2006       4           1111019       11110      종로구     당주동      19   100      세종                 104.73  3              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     267.354149   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      23        7.0
2        64560       2006       9           1111019       11110      종로구     당주동      19   100      세종                 156.74  9              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     411.892306   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      23        1.0
3        17000       2006       11          1111019       11110      종로구     당주동      19   100      세종                 91.68   4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     185.427574   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      23        6.0
4        43200       2007       1           1111019       11110      종로구     당주동      19   100      세종                 105.07  7              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     411.154468   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      24        3.0
5        44000       2007       6           1111019       11110      종로구     당주동      19   100      세종                 104.73  4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     420.127948   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      24        6.0
6        45000       2009       6           1111019       11110      종로구     당주동      19   100      세종                 102.89  4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     437.360288   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      26        6.0
7        47000       2009       9           1111019       11110      종로구     당주동      19   100      세종                 105.07  7              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     447.320834   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      26        3.0
8        74200       2009       12          1111019       11110      종로구     당주동      19   100      세종                 156.74  8              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     473.395432   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      26        2.0
9        41300       2010       3           1111019       11110      종로구     당주동      19   100      세종                 93.40   6              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     442.184154   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      27        4.0
10       47500       2010       4           1111019       11110      종로구     당주동      19   100      세종                 104.73  5              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     453.547217   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      27        5.0
11       46500       2010       4           1111019       11110      종로구     당주동      19   100      세종                 104.73  2              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     443.998854   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      27        8.0
12       41000       2011       2           1111019       11110      종로구     당주동      19   100      세종                 91.46   10             1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     448.283403   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      28        0.0
13       40000       2011       8           1111019       11110      종로구     당주동      19   100      세종                 104.73  3              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     381.934498   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      28        7.0
14       50000       2011       11          1111019       11110      종로구     당주동      19   100      세종                 104.73  2              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     477.418123   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      28        8.0
15       42000       2012       6           1111019       11110      종로구     당주동      19   100      세종                 91.68   4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     458.115183   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      29        6.0
16       50000       2012       9           1111019       11110      종로구     당주동      19   100      세종                 104.73  2              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     477.418123   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      29        8.0
17       75000       2012       12          1111019       11110      종로구     당주동      19   100      세종                 156.74  9              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     478.499426   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      29        1.0
18       42000       2012       12          1111019       11110      종로구     당주동      19   100      세종                 104.73  4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     401.031223   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      29        6.0
19       51700       2013       5           1111019       11110      종로구     당주동      19   100      세종                 104.73  5              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     493.650339   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      30        5.0
20       54200       2013       6           1111019       11110      종로구     당주동      19   100      세종                 105.07  7              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     515.846578   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      30        3.0
21       53000       2013       9           1111019       11110      종로구     당주동      19   100      세종                 104.73  4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     506.063210   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      30        6.0
22       72000       2014       3           1111019       11110      종로구     당주동      19   100      세종                 156.74  10             1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     459.359449   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      31        0.0
23       47000       2014       12          1111019       11110      종로구     당주동      19   100      세종                 91.46   10             1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     513.885852   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      31        0.0
24       57000       2015       9           1111019       11110      종로구     당주동      19   100      세종                 104.50  8              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     545.454545   서울특별시 종로구 당주동 100      서울특별시 종로구 당주동 100     NaN         1983      06      32        2.0
...        ...        ...      ..               ...         ...      ...     ...      ..   ...      ..                    ... ..               ...      ...        ...              ...        ...         ...           ...              ...        ...         ...         ...         ...         ...           ...                ...            ...          ...          ...       ...      ..       ...      ..       ...      ..       ..       ..       ..       ..        ..         ..        ..        ..        ..           ...            ...                 ...                    ...      ..          ...      ..      ..        ...
1083733  26100       2018       9           1144012       11440      마포구     서교동      12   371-7    MJ더퍼스트홍대(도시형)      14.89   8              2018     45.0        1.0             8.0        8.0        22.0           0.48          2018.07        0.0         0.0         0.0         0.0         2.0           1.0                0.0            0.0          0.0         6.0       NaN      NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN        1.0        444.0     1752.854265  서울특별시 마포구 서교동 371-7    서울특별시 마포구 서교동 371-7   NaN         2018      07      0         0.0
1083734  25400       2018       10          1144012       11440      마포구     서교동      12   371-7    MJ더퍼스트홍대(도시형)      14.89   4              2018     45.0        1.0             8.0        8.0        22.0           0.48          2018.07        0.0         0.0         0.0         0.0         2.0           1.0                0.0            0.0          0.0         6.0       NaN      NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN        1.0        444.0     1705.842848  서울특별시 마포구 서교동 371-7    서울특별시 마포구 서교동 371-7   NaN         2018      07      0         4.0
1083735  25200       2018       10          1144012       11440      마포구     서교동      12   371-7    MJ더퍼스트홍대(도시형)      14.97   7              2018     45.0        1.0             8.0        8.0        22.0           0.48          2018.07        0.0         0.0         0.0         0.0         2.0           1.0                0.0            0.0          0.0         6.0       NaN      NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN        1.0        444.0     1683.366733  서울특별시 마포구 서교동 371-7    서울특별시 마포구 서교동 371-7   NaN         2018      07      0         1.0
1083736  25800       2018       10          1144012       11440      마포구     서교동      12   371-7    MJ더퍼스트홍대(도시형)      17.46   7              2018     45.0        1.0             8.0        8.0        22.0           0.48          2018.07        0.0         0.0         0.0         0.0         2.0           1.0                0.0            0.0          0.0         6.0       NaN      NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN        1.0        444.0     1477.663230  서울특별시 마포구 서교동 371-7    서울특별시 마포구 서교동 371-7   NaN         2018      07      0         1.0

In [6]:
temp = temp.drop_duplicates()

In [7]:
temp.shape

(977228, 54)

In [8]:
pd.unique(temp['loc_code_x'])

array(['11110', '11140', '11170', '11200', '11215', '11230', '11260',
       '11290', '11305', '11320', '11350', '11380', '11440', '11470',
       '11500', '11530', '11545', '11560', '11590', '11620', '11680',
       '11710', '11740'], dtype=object)

In [9]:
pd.unique(temp['gu_list'])

array(['종로구', '중구', '용산구', '성동구', '광진구', '동대문구', '중랑구', '성북구', '강북구',
       '도봉구', '노원구', '은평구', '마포구', '양천구', '강서구', '구로구', '금천구', '영등포구',
       '동작구', '관악구', '강남구', '송파구', '강동구'], dtype=object)

In [10]:
temp.loc[:,'full_addr'] = '서울특별시 ' + temp['gu_list'] + " " + temp['law_code'] +" "+ temp['ji_bun']

In [11]:
temp.loc[:, 'entirelawcode'] = '서울특별시 ' + temp['gu_list'] + " " + temp['law_code']

In [12]:
temp.loc[:, 'yearmonth'] = temp['deal_year'].astype(str) + temp['deal_month'].astype(str)

In [13]:
list(temp)

['deal_price',
 'deal_year',
 'deal_month',
 'full_loc_code',
 'loc_code_x',
 'gu_list',
 'law_code',
 'dong',
 'ji_bun',
 'apt_name_y',
 'area',
 'current_floor',
 'build_y',
 'total_unit',
 'total_building',
 'max_floor',
 'min_floor',
 'total_parking',
 'unit_parking',
 'completed_date',
 'conv_lists',
 'medi_lists',
 'park_lists',
 'road_lists',
 'kindergarten',
 'elementary_school',
 'middle_school',
 'high_school',
 'university',
 'etc_lists',
 'S-Line1',
 'S-Line2',
 'S-Line3',
 'S-Line4',
 'S-Line5',
 'S-Line6',
 'S-Line7',
 'S-Line8',
 'S-Line9',
 'S-LineBD',
 'S-LineNBD',
 'S-LineGC',
 'S-LineJA',
 'S-LineIC',
 'S-LineAir',
 'distance',
 'avg_price',
 'full_addr',
 'apt_jibun',
 'cont_rank',
 'com_year',
 'com_mon',
 'bldg_age',
 'lv_fg',
 'entirelawcode',
 'yearmonth']

In [18]:
temp['entirelawcode']

0          서울특별시 종로구 당주동
1          서울특별시 종로구 당주동
2          서울특별시 종로구 당주동
3          서울특별시 종로구 당주동
4          서울특별시 종로구 당주동
5          서울특별시 종로구 당주동
6          서울특별시 종로구 당주동
7          서울특별시 종로구 당주동
8          서울특별시 종로구 당주동
9          서울특별시 종로구 당주동
10         서울특별시 종로구 당주동
11         서울특별시 종로구 당주동
12         서울특별시 종로구 당주동
13         서울특별시 종로구 당주동
14         서울특별시 종로구 당주동
15         서울특별시 종로구 당주동
16         서울특별시 종로구 당주동
17         서울특별시 종로구 당주동
18         서울특별시 종로구 당주동
19         서울특별시 종로구 당주동
20         서울특별시 종로구 당주동
21         서울특별시 종로구 당주동
22         서울특별시 종로구 당주동
23         서울특별시 종로구 당주동
24         서울특별시 종로구 당주동
               ...
1083733    서울특별시 마포구 서교동
1083734    서울특별시 마포구 서교동
1083735    서울특별시 마포구 서교동
1083736    서울특별시 마포구 서교동
1083737    서울특별시 마포구 서교동
1083738    서울특별시 강동구 천호동
1083739    서울특별시 종로구 평창동
1083740    서울특별시 광진구 중곡동
1083741    서울특별시 동대문구 전농동
1083742    서울특별시 동대문구 답십리동
1083743    서울특별시 동대문구 답십리동
1083744    서울특별시 동대문구 답십리동
1083745    서울특별시 동대문구 답십리동
1083746    서울특별시 동대문구 답십리동
1083747    서울특별시 은평구 대조동
1083748    서울특별시 은평구 대조동
1083749    서울특별시 은평구 대조동
1083750    서울특별시 은평구 대조동
1083751    서울특별시 강남구 역삼동
1083752    서울특별시 용산구 문배동
1083753    서울특별시 용산구 이태원동
1083754    서울특별시 동대문구 장안동
1083755    서울특별시 구로구 오류동
1083756    서울특별시 관악구 신림동
1083757    서울특별시 강동구 성내동
Name: entirelawcode, Length: 977228, dtype: object

In [16]:
# with open('merged_data(181108)_2.txt', 'wb') as f:
#     pickle.dump(temp, f)

# 법정동 코드 만들기

In [19]:
law_code = pd.read_csv('raw_code.csv')

In [20]:
temp2 = pd.merge(temp, law_code, how='inner', left_on = 'entirelawcode', right_on = '법정동명')

In [21]:
temp2.shape

(977228, 59)

In [22]:
temp2['법정동코드'] = temp2['법정동코드'].astype(int)

In [23]:
temp2['yearmonth'] = temp2['yearmonth'].astype(int)

In [24]:
temp2['current_floor'] = temp2['current_floor'].astype(int)

In [72]:
temp2['deal_price'] = temp2['deal_price'] * 10000

In [73]:
temp2.head()

   deal_price  deal_year  deal_month full_loc_code loc_code_x gu_list law_code dong ji_bun apt_name_y    area  current_floor  build_y  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineIC  S-LineAir  distance   avg_price          full_addr          apt_jibun  cont_rank  com_year com_mon  bldg_age  lv_fg  entirelawcode  yearmonth       법정동코드           법정동명 폐지여부
0  295000000   2006       1           1111019       11110      종로구     당주동      19   100    세종         93.40   6              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     315.845824  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        4.0    서울특별시 종로구 당주동  200601     1111011700  서울특별시 종로구 당주동  존재
1  280000000   2006       4           1111019       11110      종로구     당주동      19   100    세종         104.73  3              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     267.354149  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        7.0    서울특별시 종로구 당주동  200604     1111011700  서울특별시 종로구 당주동  존재
2  645600000   2006       9           1111019       11110      종로구     당주동      19   100    세종         156.74  9              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     411.892306  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        1.0    서울특별시 종로구 당주동  200609     1111011700  서울특별시 종로구 당주동  존재
3  170000000   2006       11          1111019       11110      종로구     당주동      19   100    세종         91.68   4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     185.427574  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        6.0    서울특별시 종로구 당주동  200611     1111011700  서울특별시 종로구 당주동  존재
4  432000000   2007       1           1111019       11110      종로구     당주동      19   100    세종         105.07  7              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     411.154468  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      24        3.0    서울특별시 종로구 당주동  200701     1111011700  서울특별시 종로구 당주동  존재

# 다콘을 써보자

In [27]:
da_df = pd.read_csv('../Dacon/train.csv')

In [28]:
da_df = da_df.loc[da_df['city'] == 1]

In [36]:
da_df.loc[(da_df['exclusive_use_area'] == 84.9200) & (da_df['transaction_real_price'] == 1045000000)]

             key  apartment_id  city  transaction_year_month transaction_date  year_of_completion  exclusive_use_area  floor   latitude   longitude  address_by_law  total_parking_capacity_in_site  total_household_count_in_sites  apartment_building_count_in_sites  tallest_building_in_sites  lowest_building_in_sites   heat_type heat_fuel  room_id  supply_area  total_household_count_of_area_type  room_count  bathroom_count front_door_structure  transaction_real_price
1562593  1562891  22637         1     201806                  11~20            2014                84.92               14     37.570465  127.024673  1120010100      1453.0                          1148                            14                                 25.0                       6.0                       individual  gas       19225    109.93       305                                 3.0         2.0             stairway             1045000000
1568364  1568740  22637         1     201806                  21~30            2014                84.92               15     37.570465  127.024673  1120010100      1453.0                          1148                            14                                 25.0                       6.0                       individual  gas       19225    109.93       305                                 3.0         2.0             stairway             1045000000
1600037  1602521  22637         1     201809                  1~10             2014                84.92               1      37.570465  127.024673  1120010100      1453.0                          1148                            14                                 25.0                       6.0                       individual  gas       19225    109.93       305                                 3.0         2.0             stairway             1045000000

In [30]:
da_df.head()

   key  apartment_id  city  transaction_year_month transaction_date  year_of_completion  exclusive_use_area  floor   latitude   longitude  address_by_law  total_parking_capacity_in_site  total_household_count_in_sites  apartment_building_count_in_sites  tallest_building_in_sites  lowest_building_in_sites   heat_type heat_fuel  room_id  supply_area  total_household_count_of_area_type  room_count  bathroom_count front_door_structure  transaction_real_price
0  0    5584          1     200601                  11~20            1999                47.43               6      37.585965  127.000231  1111017100      163.0                           136                             1                                  8.0                        4.0                       individual  gas       91120    65.63        46                                  1.0         1.0             corridor             215000000
1  1    5584          1     200601                  11~20            1999                44.37               8      37.585965  127.000231  1111017100      163.0                           136                             1                                  8.0                        4.0                       individual  gas       91119    61.39        10                                  2.0         1.0             corridor             200000000
2  2    5059          1     200601                  11~20            1992                54.70               8      37.580511  127.014016  1111017400      902.0                           585                             5                                  14.0                       9.0                       individual  gas       8430     72.36        201                                 2.0         1.0             corridor             168000000
3  3    2816          1     200601                  11~20            1993                64.66               11     37.580324  127.011788  1111017400      902.0                           919                             7                                  15.0                       11.0                      individual  gas       5839     87.30        284                                 2.0         1.0             corridor             165000000
4  4    2816          1     200601                  11~20            1993                106.62              7      37.580324  127.011788  1111017400      902.0                           919                             7                                  15.0                       11.0                      individual  gas       5836     127.74       112                                 4.0         2.0             stairway             280000000

In [31]:
list(da_df)

['key',
 'apartment_id',
 'city',
 'transaction_year_month',
 'transaction_date',
 'year_of_completion',
 'exclusive_use_area',
 'floor',
 'latitude',
 'longitude',
 'address_by_law',
 'total_parking_capacity_in_site',
 'total_household_count_in_sites',
 'apartment_building_count_in_sites',
 'tallest_building_in_sites',
 'lowest_building_in_sites',
 'heat_type',
 'heat_fuel',
 'room_id',
 'supply_area',
 'total_household_count_of_area_type',
 'room_count',
 'bathroom_count',
 'front_door_structure',
 'transaction_real_price']

In [32]:
da_df2 = da_df.drop(['key','apartment_id','city'], 1)

In [33]:
da_df2 = da_df2.drop_duplicates([])

In [34]:
da_df2.shape

(997175, 22)

In [46]:
temp2['deal_year'] = temp2['deal_year'].astype('str')

In [47]:
temp2['deal_month'] = temp2['deal_month'].astype('str')

In [49]:
temp2['deal_month'] = temp2['deal_month'].str.zfill(2)

In [53]:
temp2['yearmonth'] = temp2['deal_year'] + temp2['deal_month']

In [55]:
temp2['deal_year'] = temp2['deal_year'].astype(int)

In [56]:
temp2['deal_month'] = temp2['deal_month'].astype(int)

In [60]:
temp2['yearmonth'] = temp2['yearmonth'].astype(int)

In [101]:
temp2[['area', '법정동코드', 'yearmonth', 'current_floor', 'build_y', 'total_unit']].tail(10)

            area       법정동코드  yearmonth  current_floor  build_y  total_unit
977218  157.2900  1120010100  201809     23             2014     1148.0
977219  118.4900  1111011100  201412     3              2005     9.0
977220  111.3100  1111011100  201803     5              2005     9.0
977221  115.9200  1111011100  201810     4              2005     9.0
977222  18.2740   1111016200  201707     7              2017     152.0
977223  35.8451   1111016200  201710     12             2017     152.0
977224  15.8790   1111016200  201801     10             2017     152.0
977225  14.6825   1111016200  201806     7              2017     152.0
977226  15.8790   1111016200  201806     9              2017     152.0
977227  14.1832   1111016200  201807     7              2017     152.0

In [97]:
temp2.head()

   deal_price  deal_year  deal_month full_loc_code loc_code_x gu_list law_code dong ji_bun apt_name_y    area  current_floor  build_y  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineIC  S-LineAir  distance   avg_price          full_addr          apt_jibun  cont_rank  com_year com_mon  bldg_age  lv_fg  entirelawcode  yearmonth       법정동코드           법정동명 폐지여부
0  295000000   2006       1           1111019       11110      종로구     당주동      19   100    세종         93.40   6              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     315.845824  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        4.0    서울특별시 종로구 당주동  200601     1111011700  서울특별시 종로구 당주동  존재
1  280000000   2006       4           1111019       11110      종로구     당주동      19   100    세종         104.73  3              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     267.354149  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        7.0    서울특별시 종로구 당주동  200604     1111011700  서울특별시 종로구 당주동  존재
2  645600000   2006       9           1111019       11110      종로구     당주동      19   100    세종         156.74  9              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     411.892306  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        1.0    서울특별시 종로구 당주동  200609     1111011700  서울특별시 종로구 당주동  존재
3  170000000   2006       11          1111019       11110      종로구     당주동      19   100    세종         91.68   4              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     185.427574  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      23        6.0    서울특별시 종로구 당주동  200611     1111011700  서울특별시 종로구 당주동  존재
4  432000000   2007       1           1111019       11110      종로구     당주동      19   100    세종         105.07  7              1983     72.0        1.0             10.0       10.0       121.0          1.68          1983.06        1.0         0.0         7.0         0.0         2.0           1.0                0.0            0.0          0.0         16.0       1.0     NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         582.0     411.154468  서울특별시 종로구 당주동 100  서울특별시 종로구 당주동 100 NaN         1983      06      24        3.0    서울특별시 종로구 당주동  200701     1111011700  서울특별시 종로구 당주동  존재

In [98]:
da_df2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1001372 entries, 0 to 1601457
Data columns (total 24 columns):
key                                  1001372 non-null int64
apartment_id                         1001372 non-null int64
city                                 1001372 non-null int64
transaction_year_month               1001372 non-null int64
transaction_date                     1001372 non-null object
year_of_completion                   1001372 non-null int64
exclusive_use_area                   1001372 non-null float64
floor                                1001372 non-null int64
latitude                             1001372 non-null float64
longitude                            1001372 non-null float64
address_by_law                       1001372 non-null int64
total_parking_capacity_in_site       957949 non-null float64
total_household_count_in_sites       1001372 non-null int64
apartment_building_count_in_sites    1001372 non-null int64
tallest_building_in_sites            1001363 non-null float64
lowest_building_in_sites             1001363 non-null float64
heat_type                            1000640 non-null object
heat_fuel                            993902 non-null object
room_id                              1001372 non-null int64
supply_area                          1001372 non-null float64
room_count                           1000897 non-null float64
bathroom_count                       1000897 non-null float64
front_door_structure                 993574 non-null object
transaction_real_price               1001372 non-null int64
dtypes: float64(9), int64(11), object(4)
memory usage: 191.0+ MB

In [99]:
da_df2[['exclusive_use_area', 'address_by_law', 'transaction_year_month', 'floor', 'year_of_completion','total_household_count_in_sites']].head()

   exclusive_use_area  address_by_law  transaction_year_month  floor  year_of_completion  total_household_count_in_sites
0  47.43               1111017100      200601                  6      1999                136
1  44.37               1111017100      200601                  8      1999                136
2  54.70               1111017400      200601                  8      1992                585
3  64.66               1111017400      200601                  11     1993                919
4  106.62              1111017400      200601                  7      1993                919

In [88]:
da_df2 = da_df.drop('total_household_count_of_area_type', 1)

In [124]:
temp3 = pd.merge(temp2, da_df2, how='left', 
                 left_on = ['deal_price','area', '법정동코드', 'yearmonth', 'current_floor', 'build_y','total_unit'], right_on = ['transaction_real_price','exclusive_use_area', 'address_by_law', 'transaction_year_month', 'floor', 'year_of_completion','total_household_count_in_sites'])

In [125]:
# temp3 = pd.merge(temp2, da_df2, how='inner', 
#                  left_on = '법정동코드', right_on = 'address_by_law')

In [126]:
temp3.shape

(1085267, 83)

In [127]:
temp3 = temp3.drop_duplicates(temp_list)

In [129]:
temp3.shape

(647621, 83)

In [130]:
temp3.loc[temp3['loc_code_x'] == '11350']

        deal_price  deal_year  deal_month full_loc_code loc_code_x gu_list law_code dong ji_bun    apt_name_y      area  current_floor  build_y  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineIC  S-LineAir  distance   avg_price          full_addr          apt_jibun  cont_rank  com_year com_mon  bldg_age  lv_fg  entirelawcode  yearmonth       법정동코드           법정동명 폐지여부        key  apartment_id  city  transaction_year_month transaction_date  year_of_completion  exclusive_use_area  floor   latitude   longitude  address_by_law  total_parking_capacity_in_site  total_household_count_in_sites  apartment_building_count_in_sites  tallest_building_in_sites  lowest_building_in_sites   heat_type heat_fuel  room_id  supply_area  room_count  bathroom_count front_door_structure  transaction_real_price
280605  127000000   2006       1           1135003       11350      노원구     월계동      03   13     미성.           50.1400   8              1986     1620.0      16.0            14.0       5.0        1012.0         0.62          1986.05        0.0         0.0         2.0         4.0         2.0           1.0                0.0            0.0          0.0         2.0        1.0     NaN      NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         782.0     253.290786  서울특별시 노원구 월계동 13   서울특별시 노원구 월계동 13  NaN         1986      05      20        6.0    서울특별시 노원구 월계동  200601     1135010200  서울특별시 노원구 월계동  존재  NaN        NaN           NaN   NaN                      NaN             NaN                 NaN                 NaN    NaN        NaN         NaN             NaN                             NaN                             NaN                                NaN                        NaN                        NaN         NaN      NaN      NaN          NaN         NaN              NaN                 NaN
296397  148000000   2006       1           1135003       11350      노원구     월계동      03   931    장은하이빌         55.7153   8              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     265.636190  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         11.0   서울특별시 노원구 월계동  200601     1135010200  서울특별시 노원구 월계동  존재   4055.0     6216.0        1.0   200601.0                1~10             2002.0              55.7153             8.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34401.0  84.76        3.0         1.0             stairway             148000000.0
296398  200000000   2006       2           1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   18             2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     244.263472  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         1.0    서울특별시 노원구 월계동  200602     1135010200  서울특별시 노원구 월계동  존재   9911.0     6216.0        1.0   200602.0                11~20            2002.0              81.8788             18.0   37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             200000000.0
296399  138500000   2006       3           1135003       11350      노원구     월계동      03   931    장은하이빌         55.7153   6              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     248.585218  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         13.0   서울특별시 노원구 월계동  200603     1135010200  서울특별시 노원구 월계동  존재   25602.0    6216.0        1.0   200603.0                1~10             2002.0              55.7153             6.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34401.0  84.76        3.0         1.0             stairway             138500000.0
296400  108000000   2006       3           1135003       11350      노원구     월계동      03   931    장은하이빌         55.7153   1              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     193.842625  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         18.0   서울특별시 노원구 월계동  200603     1135010200  서울특별시 노원구 월계동  존재   25604.0    6216.0        1.0   200603.0                1~10             2002.0              55.7153             1.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34401.0  84.76        3.0         1.0             stairway             108000000.0
296401  217000000   2006       5           1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   8              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     265.025868  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         11.0   서울특별시 노원구 월계동  200605     1135010200  서울특별시 노원구 월계동  존재   49783.0    6216.0        1.0   200605.0                1~10             2002.0              81.8788             8.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             217000000.0
296402  154000000   2006       7           1135003       11350      노원구     월계동      03   931    장은하이빌         55.7153   5              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     276.405224  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         14.0   서울특별시 노원구 월계동  200607     1135010200  서울특별시 노원구 월계동  존재   60985.0    6216.0        1.0   200607.0                11~20            2002.0              55.7153             5.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34401.0  84.76        3.0         1.0             stairway             154000000.0
296403  215000000   2006       8           1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   17             2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     262.583233  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         2.0    서울특별시 노원구 월계동  200608     1135010200  서울특별시 노원구 월계동  존재   74149.0    6216.0        1.0   200608.0                21~31            2002.0              81.8788             17.0   37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             215000000.0
296404  150000000   2006       9           1135003       11350      노원구     월계동      03   931    장은하이빌         55.7153   4              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     269.225868  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         15.0   서울특별시 노원구 월계동  200609     1135010200  서울특별시 노원구 월계동  존재   83934.0    6216.0        1.0   200609.0                1~10             2002.0              55.7153             4.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34401.0  84.76        3.0         1.0             stairway             150000000.0
296405  212500000   2006       11          1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   2              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     259.529939  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         17.0   서울특별시 노원구 월계동  200611     1135010200  서울특별시 노원구 월계동  존재   127341.0   6216.0        1.0   200611.0                1~10             2002.0              81.8788             2.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             212500000.0
296406  220000000   2006       11          1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   18             2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     268.689820  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         1.0    서울특별시 노원구 월계동  200611     1135010200  서울특별시 노원구 월계동  존재   127347.0   6216.0        1.0   200611.0                1~10             2002.0              81.8788             18.0   37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             220000000.0
296407  228000000   2006       11          1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   16             2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     278.460358  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         3.0    서울특별시 노원구 월계동  200611     1135010200  서울특별시 노원구 월계동  존재   118452.0   6216.0        1.0   200611.0                11~20            2002.0              81.8788             16.0   37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             228000000.0
296409  259000000   2006       12          1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   9              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     316.321197  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      4         10.0   서울특별시 노원구 월계동  200612     1135010200  서울특별시 노원구 월계동  존재   142218.0   6216.0        1.0   200612.0                1~10             2002.0              81.8788             9.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             259000000.0
296410  320000000   2007       4           1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   11             2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     390.821556  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      5         8.0    서울특별시 노원구 월계동  200704     1135010200  서울특별시 노원구 월계동  존재   171295.0   6216.0        1.0   200704.0                1~10             2002.0              81.8788             11.0   37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             320000000.0
296411  260000000   2007       6           1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   4              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     317.542514  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      5         15.0   서울특별시 노원구 월계동  200706     1135010200  서울특별시 노원구 월계동  존재   183982.0   6216.0        1.0   200706.0                1~10             2002.0              81.8788             4.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             260000000.0
296412  177000000   2007       6           1135003       11350      노원구     월계동      03   931    장은하이빌         55.7153   2              2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     317.686524  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      5         17.0   서울특별시 노원구 월계동  200706     1135010200  서울특별시 노원구 월계동  존재   181826.0   6216.0        1.0   200706.0                11~20            2002.0              55.7153             2.0    37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34401.0  84.76        3.0         1.0             stairway             177000000.0
296413  280000000   2007       8           1135003       11350      노원구     월계동      03   931    장은하이빌         81.8788   14             2002     105.0       2.0             19.0       9.0        105.0          1.00          2002.05        1.0         0.0         1.0         0.0         2.0           1.0                1.0            1.0          1.0         1.0        1.0     NaN      NaN      NaN      NaN       1.0     NaN      NaN      NaN      NaN       NaN         1.0      NaN       NaN       NaN         601.5     341.968861  서울특별시 노원구 월계동 931  서울특별시 노원구 월계동 931 NaN         2002      05      5         5.0    서울특별시 노원구 월계동  200708     1135010200  서울특별시 노원구 월계동  존재   196844.0   6216.0        1.0   200708.0                11~20            2002.0              81.8788             14.0   37.620641  127.061788  1.135010e+09    105.0                           105.0                           2.0                                19.0                       9.0                       individual  gas       34402.0  111.04       3.0         2.0             stairway             280000000.0

In [84]:
temp3[['max_floor', 'min_floor', 'tallest_building_in_sites', 'lowest_building_in_sites']]

,max_floor,min_floor,tallest_building_in_sites,lowest_building_in_sites
0,9.0,3.0,9.0,3.0
1,9.0,3.0,9.0,3.0
2,9.0,3.0,9.0,3.0
3,9.0,3.0,9.0,3.0
4,9.0,3.0,9.0,3.0
5,9.0,3.0,9.0,3.0
6,9.0,3.0,9.0,3.0
7,9.0,3.0,9.0,3.0
8,9.0,3.0,9.0,3.0
9,9.0,3.0,9.0,3.0
10,9.0,3.0,9.0,3.0
11,9.0,3.0,9.0,3.0
12,9.0,3.0,9.0,3.0
13,9.0,3.0,9.0,3.0
14,9.0,3.0,9.0,3.0
15,9.0,3.0,9.0,3.0
16,9.0,3.0,9.0,3.0
17,9.0,3.0,9.0,3.0
18,9.0,3.0,9.0,3.0
19,9.0,3.0,9.0,3.0
20,9.0,3.0,9.0,3.0
21,9.0,3.0,9.0,3.0
22,9.0,3.0,9.0,3.0
23,9.0,3.0,9.0,3.0
24,9.0,3.0,9.0,3.0
25,9.0,3.0,9.0,3.0
26,9.0,3.0,9.0,3.0
27,9.0,3.0,9.0,3.0
28,9.0,3.0,9.0,3.0
29,9.0,3.0,9.0,3.0
...,...,...,...,...
554003,25.0,6.0,25.0,6.0
554004,25.0,6.0,25.0,6.0
554005,25.0,6.0,25.0,6.0
554006,25.0,6.0,25.0,6.0
554007,25.0,6.0,25.0,6.0
554008,25.0,6.0,25.0,6.0
554009,25.0,6.0,25.0,6.0
554010,25.0,6.0,25.0,6.0
554011,25.0,6.0,25.0,6.0
554012,25.0,6.0,25.0,6.0
554013,25.0,6.0,25.0,6.0
554014,25.0,6.0,25.0,6.0
554015,25.0,6.0,25.0,6.0
554016,25.0,6.0,25.0,6.0
554017,25.0,6.0,25.0,6.0
554018,25.0,6.0,25.0,6.0
554019,25.0,6.0,25.0,6.0
554020,25.0,6.0,25.0,6.0
554021,25.0,6.0,25.0,6.0
554022,25.0,6.0,25.0,6.0
554023,25.0,6.0,25.0,6.0
554024,25.0,6.0,25.0,6.0
554025,25.0,6.0,25.0,6.0
554026,25.0,6.0,25.0,6.0
554027,25.0,6.0,25.0,6.0
554028,25.0,6.0,25.0,6.0
554029,25.0,6.0,25.0,6.0
554030,25.0,6.0,25.0,6.0
554031,25.0,6.0,25.0,6.0
554032,25.0,6.0,25.0,6.0

In [85]:
list(temp3)

['deal_price',
 'deal_year',
 'deal_month',
 'full_loc_code',
 'loc_code_x',
 'gu_list',
 'law_code',
 'dong',
 'ji_bun',
 'apt_name_y',
 'area',
 'current_floor',
 'build_y',
 'total_unit',
 'total_building',
 'max_floor',
 'min_floor',
 'total_parking',
 'unit_parking',
 'completed_date',
 'conv_lists',
 'medi_lists',
 'park_lists',
 'road_lists',
 'kindergarten',
 'elementary_school',
 'middle_school',
 'high_school',
 'university',
 'etc_lists',
 'S-Line1',
 'S-Line2',
 'S-Line3',
 'S-Line4',
 'S-Line5',
 'S-Line6',
 'S-Line7',
 'S-Line8',
 'S-Line9',
 'S-LineBD',
 'S-LineNBD',
 'S-LineGC',
 'S-LineJA',
 'S-LineIC',
 'S-LineAir',
 'distance',
 'full_address',
 'price_yard',
 'deal_date',
 'full_addr',
 'entirelawcode',
 'yearmonth',
 '법정동코드',
 '법정동명',
 '폐지여부',
 'transaction_year_month',
 'transaction_date',
 'year_of_completion',
 'exclusive_use_area',
 'floor',
 'latitude',
 'longitude',
 'address_by_law',
 'total_parking_capacity_in_site',
 'total_household_count_in_sites',
 'apartment_building_count_in_sites',
 'tallest_building_in_sites',
 'lowest_building_in_sites',
 'heat_type',
 'heat_fuel',
 'room_id',
 'supply_area',
 'total_household_count_of_area_type',
 'room_count',
 'bathroom_count',
 'front_door_structure',
 'transaction_real_price']

In [131]:
with open('./datawithouterror_1203.txt', 'rb') as f:
    temp4 = pickle.load(f)

In [135]:
temp4

        deal_price  deal_year  deal_month full_loc_code loc_code_x gu_list law_code dong ji_bun apt_name_y    area  current_floor  build_y  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineIC  S-LineAir  distance         full_address   price_yard  deal_date            full_addr    entirelawcode  yearmonth       법정동코드             법정동명 폐지여부  transaction_year_month transaction_date  year_of_completion  exclusive_use_area  floor   latitude   longitude  address_by_law  total_parking_capacity_in_site  total_household_count_in_sites  apartment_building_count_in_sites  tallest_building_in_sites  lowest_building_in_sites   heat_type heat_fuel  room_count  bathroom_count front_door_structure  transaction_real_price
0       150000000   2006       4           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   5              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     309.023486  2006-04-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200604     1111013300  서울특별시 종로구 익선동    존재   200604                  11~20            2003                48.54               5      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             150000000
1       148000000   2006       5           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     46.64   3              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     317.324185  2006-05-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200605     1111013300  서울특별시 종로구 익선동    존재   200605                  21~31            2003                46.64               3      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             148000000
2       150000000   2006       8           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     45.50   3              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     329.670330  2006-08-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200608     1111013300  서울특별시 종로구 익선동    존재   200608                  11~20            2003                45.50               3      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             150000000
3       160000000   2006       9           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     46.64   2              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     343.053173  2006-09-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200609     1111013300  서울특별시 종로구 익선동    존재   200609                  21~30            2003                46.64               2      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             160000000
4       120000000   2006       9           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     36.08   7              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     332.594235  2006-09-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200609     1111013300  서울특별시 종로구 익선동    존재   200609                  21~30            2003                36.08               7      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             120000000
5       172840000   2006       10          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   6              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     356.077462  2006-10-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200610     1111013300  서울특별시 종로구 익선동    존재   200610                  1~10             2003                48.54               6      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             172840000
6       165130000   2006       10          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     45.50   7              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     362.923077  2006-10-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200610     1111013300  서울특별시 종로구 익선동    존재   200610                  1~10             2003                45.50               7      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             165130000
7       153000000   2006       10          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     46.64   3              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     328.044597  2006-10-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200610     1111013300  서울특별시 종로구 익선동    존재   200610                  11~20            2003                46.64               3      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             153000000
8       180000000   2006       10          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   6              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     370.828183  2006-10-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200610     1111013300  서울특별시 종로구 익선동    존재   200610                  11~20            2003                48.54               6      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             180000000
9       110000000   2006       11          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     28.10   9              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     391.459075  2006-11-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200611     1111013300  서울특별시 종로구 익선동    존재   200611                  1~10             2003                28.10               9      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             110000000
10      170000000   2006       12          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   8              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     350.226617  2006-12-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200612     1111013300  서울특별시 종로구 익선동    존재   200612                  11~20            2003                48.54               8      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             170000000
11      165000000   2006       12          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     46.64   2              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     353.773585  2006-12-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200612     1111013300  서울특별시 종로구 익선동    존재   200612                  21~31            2003                46.64               2      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             165000000
12      170000000   2006       12          1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   5              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     350.226617  2006-12-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200612     1111013300  서울특별시 종로구 익선동    존재   200612                  21~31            2003                48.54               5      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             170000000
13      150000000   2007       1           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   4              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     309.023486  2007-01-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200701     1111013300  서울특별시 종로구 익선동    존재   200701                  11~20            2003                48.54               4      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             150000000
14      165000000   2007       1           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   8              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     339.925834  2007-01-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200701     1111013300  서울특별시 종로구 익선동    존재   200701                  11~20            2003                48.54               8      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             165000000
15      180000000   2007       1           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   8              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     370.828183  2007-01-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200701     1111013300  서울특별시 종로구 익선동    존재   200701                  11~20            2003                48.54               8      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             180000000
16      180000000   2007       1           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     48.54   9              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     370.828183  2007-01-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200701     1111013300  서울특별시 종로구 익선동    존재   200701                  11~20            2003                48.54               9      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             180000000
17      145000000   2007       2           1111051       11110      종로구     익선동      51   55     현대뜨레비앙     43.98   6              2003     291.0       1.0             9.0        3.0        228.0          0.78          2003.11        0.0         1.0         3.0         0.0         1.0           1.0                0.0            0.0          1.0         11.0      NaN      NaN       1.0     NaN       1.0     NaN      NaN      NaN      NaN      NaN       NaN        NaN       NaN       NaN       NaN         350.00    서울특별시 종로구 익선동 55     329.695316  2007-02-01  서울특별시 종로구 익선동 55     서울특별시 종로구 익선동    200702     1111013300  서울특별시 종로구 익선동    존재   200702                  1~10             2003                43.98               6      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             145000000

In [3]:
with open('./data_without_error_1203_full_name.txt', 'rb') as f:
    temp5 = pickle.load(f)

In [7]:
pd.set_option('display.max_columns', None)  
pd.set_option('display.expand_frame_repr', False)
pd.set_option('max_colwidth', -1)

In [6]:
temp5.columns.values

array(['deal_price', 'deal_year', 'deal_month', 'full_loc_code',
       'loc_code_x', 'dong', 'ji_bun', 'apt_name_y', 'area',
       'current_floor', 'total_unit', 'total_building', 'max_floor',
       'min_floor', 'total_parking', 'unit_parking', 'completed_date',
       'conv_lists', 'medi_lists', 'park_lists', 'road_lists',
       'kindergarten', 'elementary_school', 'middle_school',
       'high_school', 'university', 'etc_lists', 'S-Line1', 'S-Line2',
       'S-Line3', 'S-Line4', 'S-Line5', 'S-Line6', 'S-Line7', 'S-Line8',
       'S-Line9', 'S-LineBD', 'S-LineNBD', 'S-LineGC', 'S-LineJA',
       'S-LineAir', 'distance', 'full_address', 'price_yard', 'deal_date',
       'full_addr', 'entirelawcode', 'yearmonth', '법정동코드', '법정동명', '폐지여부',
       'transaction_year_month', 'transaction_date', 'year_of_completion',
       'exclusive_use_area', 'floor', 'latitude', 'longitude',
       'address_by_law', 'total_parking_capacity_in_site',
       'total_household_count_in_sites',
       'apartment_building_count_in_sites', 'tallest_building_in_sites',
       'lowest_building_in_sites', 'heat_type', 'heat_fuel', 'room_count',
       'bathroom_count', 'front_door_structure', 'transaction_real_price',
       'cont_rank', 'com_year', 'com_mon', 'avg_price', 'sub_num',
       'bldg_age', 'lv_fg'], dtype=object)

In [9]:
temp5.head(1)

   deal_price  deal_year  deal_month full_loc_code  loc_code_x  dong ji_bun apt_name_y  area  current_floor  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineAir  distance      full_address  price_yard  deal_date         full_addr  entirelawcode  yearmonth       법정동코드           법정동명 폐지여부  transaction_year_month transaction_date  year_of_completion  exclusive_use_area  floor   latitude   longitude  address_by_law  total_parking_capacity_in_site  total_household_count_in_sites  apartment_building_count_in_sites  tallest_building_in_sites  lowest_building_in_sites   heat_type heat_fuel  room_count  bathroom_count front_door_structure  transaction_real_price  cont_rank  com_year  com_mon  avg_price  sub_num  bldg_age     lv_fg
0  150000000   2006       4           1111051       11110       51    55     현대뜨레비앙     48    5              291         1               9          3          228            0             2003.11        0           1           3           0           1             1                  0              0            1           11         0        0        1        0        1        0        0        0        0        0         0          0         0         0          350       서울특별시 종로구 익선동 55  309.023486 2006-04-01  서울특별시 종로구 익선동 55  서울특별시 종로구 익선동  200604     1111013300  서울특별시 종로구 익선동  존재   200604                  11~20            2003                48.54               5      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             150000000               2          2003      11       3090234    2        3         0.555556

### 중복 제거 해보자

1. area vs exclusive_use_area

1.1 exclusive_use_area 가 더 정확 float ->  area 삭제

In [10]:
temp5 = temp5.drop('area', 1)

2. 기타 불필요 일단 선 제거

In [143]:
temp5 = temp5.drop(['deal_date', '법정동명', '폐지여부', 'transaction_real_price','apartment_building_count_in_sites','tallest_building_in_sites','lowest_building_in_sites'], 1)

In [145]:
temp5 = temp5.drop(['total_household_count_in_sites', 'transaction_date', 'year_of_completion', 'yearmonth'], 1)

In [147]:
temp5 = temp5.drop(['법정동코드', 'total_parking_capacity_in_site'], 1)

In [150]:
temp5 = temp5.drop(['transaction_year_month'], 1)

In [153]:
temp5 = temp5.drop(['entirelawcode'], 1)

In [155]:
temp5 = temp5.drop('loc_code_x', 1)

3. 가격 단위 변경

In [157]:
temp5['deal_price'] = temp5['deal_price'] / 10000

In [141]:
list(temp5)

['deal_price',
 'deal_year',
 'deal_month',
 'loc_code_x',
 'dong',
 'current_floor',
 'total_unit',
 'total_building',
 'max_floor',
 'min_floor',
 'total_parking',
 'unit_parking',
 'conv_lists',
 'medi_lists',
 'park_lists',
 'road_lists',
 'kindergarten',
 'elementary_school',
 'middle_school',
 'high_school',
 'university',
 'etc_lists',
 'S-Line1',
 'S-Line2',
 'S-Line3',
 'S-Line4',
 'S-Line5',
 'S-Line6',
 'S-Line7',
 'S-Line8',
 'S-Line9',
 'S-LineBD',
 'S-LineNBD',
 'S-LineGC',
 'S-LineJA',
 'S-LineAir',
 'distance',
 'deal_date',
 'entirelawcode',
 'yearmonth',
 '법정동코드',
 '법정동명',
 '폐지여부',
 'transaction_year_month',
 'transaction_date',
 'year_of_completion',
 'exclusive_use_area',
 'floor',
 'latitude',
 'longitude',
 'address_by_law',
 'total_parking_capacity_in_site',
 'total_household_count_in_sites',
 'apartment_building_count_in_sites',
 'tallest_building_in_sites',
 'lowest_building_in_sites',
 'heat_type',
 'heat_fuel',
 'room_count',
 'bathroom_count',
 'front_door_structure',
 'transaction_real_price',
 'cont_rank',
 'com_year',
 'com_mon',
 'avg_price',
 'sub_num',
 'bldg_age',
 'lv_fg']

In [11]:
ht = pd.get_dummies(temp5['heat_type'])

In [12]:
ht.columns = ['ht_cnr', 'ht_dst', 'ht_indv']

In [13]:
fuel = pd.get_dummies(temp5['heat_fuel'])

In [14]:
fuel.columns = ['fuel_un', 'fuel_cog', 'fuel_gas']

In [15]:
stair_type = pd.get_dummies(temp5['front_door_structure'])

In [16]:
stair_type.columns = ['stair_un','corridor','mixed','stairway']

In [17]:
stair_type

        stair_un  corridor  mixed  stairway
0       0         1         0      0
1       0         1         0      0
2       0         1         0      0
3       0         1         0      0
4       0         1         0      0
5       0         1         0      0
6       0         1         0      0
7       0         1         0      0
8       0         1         0      0
9       0         1         0      0
10      0         1         0      0
11      0         1         0      0
12      0         1         0      0
13      0         1         0      0
14      0         1         0      0
15      0         1         0      0
16      0         1         0      0
17      0         1         0      0
18      0         1         0      0
19      0         1         0      0
20      0         1         0      0
21      0         1         0      0
22      0         1         0      0
23      0         1         0      0
24      0         1         0      0
25      0         1         0      0
26      0         1         0      0
27      0         1         0      0
28      0         1         0      0
29      0         1         0      0
...    ..        ..        ..     ..
908131  0         0         0      1
908132  0         0         0      1
908133  0         0         0      1
908134  0         0         0      1
908135  0         0         0      1
908136  0         0         0      1
908137  0         0         0      1
908138  0         0         0      1
908139  0         0         0      1
908140  0         0         0      1
908141  0         0         0      1
908142  0         0         0      1
908143  0         0         0      1
908144  0         0         0      1
908145  0         0         0      1
908146  0         0         0      1
908147  0         0         0      1
908148  0         0         0      1
908149  0         0         0      1
908150  0         0         0      1
908151  0         0         0      1
908152  0         0         0      1
908153  0         0         0      1
908154  0         0         0      1
908155  0         0         0      1
908156  0         0         0      1
908157  0         0         0      1
908158  0         0         0      1
908159  0         0         0      1
908160  0         0         0      1

[908161 rows x 4 columns]

In [18]:
temp6 = pd.concat([temp5, ht], axis=1)

In [19]:
temp7 = pd.concat([temp6, fuel], axis=1)

In [20]:
temp8 = pd.concat([temp7, stair_type], axis=1)

In [190]:
temp8 = temp8.drop(['heat_type', 'heat_fuel', 'front_door_structure'] ,1)

In [192]:
temp8 = temp8.drop(['floor'], 1)

In [194]:
temp8.to_csv('fin_data.csv')

In [22]:
temp8.to_csv('FIRA_FIN.csv')

In [23]:
with open('FIRA_FIN.txt', 'wb') as f:
    pickle.dump(temp8, f)

In [300]:
addr = '서울특별시 강남구 개포동 189'
apt_name = '개포주공(4단지)'
area = 35.87

In [301]:
a_condi = (temp8['apt_name_y'] == apt_name) & (temp8['full_addr'] == addr) & (temp8['exclusive_use_area'] == area)

In [260]:
temp8.head(1)

   deal_price  deal_year  deal_month full_loc_code  loc_code_x  dong ji_bun apt_name_y  current_floor  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking completed_date  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineAir  distance      full_address  price_yard  deal_date         full_addr  entirelawcode  yearmonth       법정동코드           법정동명 폐지여부  transaction_year_month transaction_date  year_of_completion  exclusive_use_area  floor   latitude   longitude  address_by_law  total_parking_capacity_in_site  total_household_count_in_sites  apartment_building_count_in_sites  tallest_building_in_sites  lowest_building_in_sites   heat_type heat_fuel  room_count  bathroom_count front_door_structure  transaction_real_price  cont_rank  com_year  com_mon  avg_price  sub_num  bldg_age     lv_fg  ht_cnr  ht_dst  ht_indv  fuel_un  fuel_cog  fuel_gas  stair_un  corridor  mixed  stairway
0  150000000   2006       4           1111051       11110       51    55     현대뜨레비앙     5              291         1               9          3          228            0             2003.11        0           1           3           0           1             1                  0              0            1           11         0        0        1        0        1        0        0        0        0        0         0          0         0         0          350       서울특별시 종로구 익선동 55  309.023486 2006-04-01  서울특별시 종로구 익선동 55  서울특별시 종로구 익선동  200604     1111013300  서울특별시 종로구 익선동  존재   200604                  11~20            2003                48.54               5      37.575113  126.990056  1111013300      228.0                           291                             1                                  9.0                        3.0                       individual  gas       1.0         1.0             corridor             150000000               2          2003      11       3090234    2        3         0.555556  0       0       1        0        0         1         0         1         0      0

In [198]:
temp8.columns.values

array(['deal_price', 'deal_year', 'deal_month', 'full_loc_code',
       'loc_code_x', 'dong', 'ji_bun', 'apt_name_y', 'current_floor',
       'total_unit', 'total_building', 'max_floor', 'min_floor',
       'total_parking', 'unit_parking', 'completed_date', 'conv_lists',
       'medi_lists', 'park_lists', 'road_lists', 'kindergarten',
       'elementary_school', 'middle_school', 'high_school', 'university',
       'etc_lists', 'S-Line1', 'S-Line2', 'S-Line3', 'S-Line4', 'S-Line5',
       'S-Line6', 'S-Line7', 'S-Line8', 'S-Line9', 'S-LineBD',
       'S-LineNBD', 'S-LineGC', 'S-LineJA', 'S-LineAir', 'distance',
       'full_address', 'price_yard', 'deal_date', 'full_addr',
       'entirelawcode', 'yearmonth', '법정동코드', '법정동명', '폐지여부',
       'transaction_year_month', 'transaction_date', 'year_of_completion',
       'exclusive_use_area', 'floor', 'latitude', 'longitude',
       'address_by_law', 'total_parking_capacity_in_site',
       'total_household_count_in_sites',
       'apartment_building_count_in_sites', 'tallest_building_in_sites',
       'lowest_building_in_sites', 'heat_type', 'heat_fuel', 'room_count',
       'bathroom_count', 'front_door_structure', 'transaction_real_price',
       'cont_rank', 'com_year', 'com_mon', 'avg_price', 'sub_num',
       'bldg_age', 'lv_fg', 'ht_cnr', 'ht_dst', 'ht_indv', 'fuel_un',
       'fuel_cog', 'fuel_gas', 'stair_un', 'corridor', 'mixed',
       'stairway'], dtype=object)

In [199]:
static_columns = ['address_by_law','full_addr', 'apt_name_y', 'total_unit', 'total_building', 'max_floor', 'min_floor',
       'total_parking', 'unit_parking', 'conv_lists',
       'medi_lists', 'park_lists', 'road_lists', 'kindergarten',
       'elementary_school', 'middle_school', 'high_school', 'university',
       'etc_lists', 'S-Line1', 'S-Line2', 'S-Line3', 'S-Line4', 'S-Line5',
       'S-Line6', 'S-Line7', 'S-Line8', 'S-Line9', 'S-LineBD',
       'S-LineNBD', 'S-LineGC', 'S-LineJA', 'S-LineAir', 'distance','latitude', 'longitude','room_count',
       'bathroom_count','cont_rank', 'com_year', 'com_mon','sub_num',
       'ht_cnr', 'ht_dst', 'ht_indv', 'fuel_un',
       'fuel_cog', 'fuel_gas', 'stair_un', 'corridor', 'mixed',
       'stairway']

$scope.sub_max = 5;
$scope.sub_mean = 1.54;
$scope.conv_max = 8;
$scope.conv_mean = 1.23;
$scope.medi_max = 4;
$scope.medi_mean = 0.53;
$scope.park_max = 8;
$scope.park_mean = 1.51;
$scope.road_max = 10;
$scope.road_mean = 1.09;

In [329]:
temp8['sub_num'].mean()

1.5444111781941747

In [328]:
temp8['distance'].min()

0

In [330]:
temp8['conv_lists'].mean()

1.2326746028512565

In [331]:
temp8['medi_lists'].mean()

0.5377812964881777

In [332]:
temp8['park_lists'].mean()

1.5136203822890435

In [333]:
temp8['road_lists'].mean()

1.093135468270494

In [270]:
tk = temp8['exclusive_use_area'][a_condi]

In [271]:
tk.unique()

array([208.478])

In [302]:
search_final = temp8[static_columns][a_condi].drop_duplicates()

In [305]:
search_final[:1][:]

        address_by_law          full_addr apt_name_y  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineAir  distance   latitude   longitude  room_count  bathroom_count  cont_rank  com_year  com_mon  sub_num  ht_cnr  ht_dst  ht_indv  fuel_un  fuel_cog  fuel_gas  stair_un  corridor  mixed  stairway
744966  1168010300      서울특별시 강남구 개포동 189  개포주공(4단지)  2840        58              5          5          1136           0             0           0           0           0           2             1                  0              1            0           1          0        0        0        0        0        0        0        0        0        1         0          0         0         0          559       37.486331  127.073169  2.0         1.0             1000       1982      11       1        0       0       1        0        0         1         0         0         0      1

In [299]:
search_final = pd.DataFrame(search_final.iloc[0])

In [297]:
search_final.iloc[0]

address_by_law       1117013100
full_addr            서울특별시 용산구 한남동 810
apt_name_y           한남더힐
total_unit           600
total_building       32
max_floor            12
min_floor            1
total_parking        1732
unit_parking         2
conv_lists           3
medi_lists           0
park_lists           2
road_lists           0
kindergarten         1
elementary_school    1
middle_school        0
high_school          0
university           0
etc_lists            0
S-Line1              0
S-Line2              0
S-Line3              1
S-Line4              0
S-Line5              0
S-Line6              1
S-Line7              0
S-Line8              0
S-Line9              0
S-LineBD             0
S-LineNBD            0
S-LineGC             0
S-LineJA             1
S-LineAir            0
distance             975
latitude             37.537
longitude            127.009
room_count           5
bathroom_count       2
cont_rank            4
com_year             2011
com_mon              1
sub_num              3
ht_cnr               0
ht_dst               0
ht_indv              1
fuel_un              0
fuel_cog             0
fuel_gas             1
stair_un             0
corridor             0
mixed                0
stairway             1
Name: 21179, dtype: object

In [202]:
dynamic_columns = [
    'current_floor','lv_fg','law_dong', 'deal_year', 'deal_month', 'exclusive_use_area'
]

In [203]:
final_columns = ['deal_year', 'deal_month', 'current_floor', 'total_unit',
       'total_building', 'max_floor', 'min_floor', 'total_parking',
       'unit_parking', 'conv_lists', 'medi_lists', 'park_lists',
       'road_lists', 'kindergarten', 'elementary_school', 'middle_school',
       'high_school', 'university', 'etc_lists', 'S-Line1', 'S-Line2',
       'S-Line3', 'S-Line4', 'S-Line5', 'S-Line6', 'S-Line7', 'S-Line8',
       'S-Line9', 'S-LineBD', 'S-LineNBD', 'S-LineGC', 'S-LineJA',
       'S-LineAir', 'distance', 'exclusive_use_area', 'latitude',
       'longitude', 'room_count', 'bathroom_count', 'cont_rank',
       'com_year', 'com_mon', 'sub_num', 'bldg_age', 'lv_fg', 'ht_cnr',
       'ht_dst', 'ht_indv', 'fuel_un', 'fuel_cog', 'fuel_gas', 'stair_un',
       'corridor', 'mixed', 'stairway', 'law_dong', 'gu_val', 'jisu',
       'tonghwa', 'sobi1', 'sobi2']

In [204]:
idx_range = [0]
empty_df = pd.DataFrame(columns=final_columns, index=idx_range)
empty_df = empty_df.fillna(0)

In [217]:
float_list = ["latitude", "longitude", "room_count", "bathroom_count", "lv_fg", "gu_val", 'jisu',
       'tonghwa', 'sobi1', 'sobi2', 'exclusive_use_area']

In [218]:
for ft in float_list:
    empty_df[ft] =  empty_df[ft].astype(float)

In [219]:
for col_name in static_columns[3:]:
    empty_df.loc[:][col_name] = search_final[col_name].values

In [208]:
# 사용자 입력

In [250]:
empty_df.loc[:]['current_floor'] = 10
empty_df.loc[:]['deal_year'] = 2018
empty_df.loc[:]['deal_month'] = 10
empty_df.loc[:]['exclusive_use_area'] = 153.80

In [251]:
one_hot_list = [
    'ht_cnr', 'ht_dst', 'ht_indv', 'fuel_un', 'fuel_cog', 'fuel_gas', 'stair_un','corridor', 'mixed', 'stairway'
]

In [252]:
empty_df.loc[:]['gu_val'] = 3.096711288582110
empty_df.loc[:]['jisu'] = 109.2
empty_df.loc[:]['tonghwa'] = 3734526.2 / 1000000
empty_df.loc[:]['sobi1'] = 104.46
empty_df.loc[:]['sobi2'] = 115.10

In [233]:
for col_name in one_hot_list:
    empty_df[col_name] = search_final[col_name].values

In [234]:
empty_df.loc[:]['bldg_age'] = 2018 - empty_df['com_year'].values
empty_df.loc[:]['lv_fg'] = empty_df['current_floor'].values / empty_df['max_floor'].values
empty_df.loc[:]['law_dong'] = (search_final['address_by_law'].values % 10000) // 100

In [253]:
empty_df

   deal_year  deal_month  current_floor  total_unit  total_building  max_floor  min_floor  total_parking  unit_parking  conv_lists  medi_lists  park_lists  road_lists  kindergarten  elementary_school  middle_school  high_school  university  etc_lists  S-Line1  S-Line2  S-Line3  S-Line4  S-Line5  S-Line6  S-Line7  S-Line8  S-Line9  S-LineBD  S-LineNBD  S-LineGC  S-LineJA  S-LineAir  distance  exclusive_use_area   latitude   longitude  room_count  bathroom_count  cont_rank  com_year  com_mon  sub_num  bldg_age     lv_fg  ht_cnr  ht_dst  ht_indv  fuel_un  fuel_cog  fuel_gas  stair_un  corridor  mixed  stairway  law_dong    gu_val   jisu   tonghwa   sobi1  sobi2
0  2018       10          10             212         4               22         20         502            2             2           0           4           4           0             1                  0              1            0           0          0        0        1        0        0        0        0        0        0        1         0          0         0         0          684       153.8               37.496298  127.076626  4.0         2.0             5          2004      6        2        14        0.454545  0       1       0        0        1         0         0         0         0      1         3         3.096711  109.2  3.734526  104.46  115.1

In [236]:
len(empty_df.columns.values)

61

## model load

In [308]:
import os

In [309]:
os.environ['KERAS_BACKEND'] = 'theano'

In [314]:
import keras

In [315]:
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import ModelCheckpoint
from keras.models import model_from_json

In [311]:
json_file = open("./Gangnam_model.json", "r")
loaded_model_json = json_file.read()
json_file.close() 
loaded_model = model_from_json(loaded_model_json)

In [312]:
loaded_model.load_weights("./Gangnam_model.hdf5")

In [313]:
loaded_model.predict(empty_df)[0][0]

193932.12

In [24]:
with open('/Users/tax_k/Projects/AI-DL/KB/deal_only_info.txt', 'rb') as f:
    deal_only_list = pickle.load(f)

In [25]:
search_list = deal_only_list[(deal_only_list['full_address'] == '서울특별시 종로구 익선동 55') & (deal_only_list['apt_name_y'] == '현대뜨레비앙')]

In [26]:
search_list

            full_address apt_name_y  floor  exclusive_use_area  deal_date  deal_year  deal_month  deal_price  billion  thousand
28260   서울특별시 종로구 익선동 55  현대뜨레비앙     3      58.78              2018-05-01  2018       5           44000.0     4.0      4000.0
32239   서울특별시 종로구 익선동 55  현대뜨레비앙     3      48.54              2018-04-01  2018       4           29995.0     2.0      9995.0
35927   서울특별시 종로구 익선동 55  현대뜨레비앙     6      43.98              2018-03-01  2018       3           26800.0     2.0      6800.0
35928   서울특별시 종로구 익선동 55  현대뜨레비앙     9      28.10              2018-03-01  2018       3           23000.0     2.0      3000.0
44026   서울특별시 종로구 익선동 55  현대뜨레비앙     7      48.54              2018-02-01  2018       2           30000.0     3.0      0.0
52350   서울특별시 종로구 익선동 55  현대뜨레비앙     5      46.64              2018-01-01  2018       1           29000.0     2.0      9000.0
52351   서울특별시 종로구 익선동 55  현대뜨레비앙     6      36.08              2018-01-01  2018       1           23500.0     2.0      3500.0
72296   서울특별시 종로구 익선동 55  현대뜨레비앙     6      48.54              2017-11-01  2017       11          29990.0     2.0      9990.0
72297   서울특별시 종로구 익선동 55  현대뜨레비앙     6      48.54              2017-11-01  2017       11          29990.0     2.0      9990.0
72298   서울특별시 종로구 익선동 55  현대뜨레비앙     4      46.64              2017-11-01  2017       11          29300.0     2.0      9300.0
72299   서울특별시 종로구 익선동 55  현대뜨레비앙     7      45.50              2017-11-01  2017       11          29000.0     2.0      9000.0
80062   서울특별시 종로구 익선동 55  현대뜨레비앙     3      48.54              2017-10-01  2017       10          28500.0     2.0      8500.0
92255   서울특별시 종로구 익선동 55  현대뜨레비앙     7      43.98              2017-08-01  2017       8           25000.0     2.0      5000.0
96745   서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2017-07-01  2017       7           28100.0     2.0      8100.0
96746   서울특별시 종로구 익선동 55  현대뜨레비앙     7      36.08              2017-07-01  2017       7           23500.0     2.0      3500.0
96747   서울특별시 종로구 익선동 55  현대뜨레비앙     8      48.54              2017-07-01  2017       7           29000.0     2.0      9000.0
110828  서울특별시 종로구 익선동 55  현대뜨레비앙     7      36.08              2017-06-01  2017       6           23000.0     2.0      3000.0
145841  서울특별시 종로구 익선동 55  현대뜨레비앙     7      48.54              2017-03-01  2017       3           27800.0     2.0      7800.0
145842  서울특별시 종로구 익선동 55  현대뜨레비앙     4      46.64              2017-03-01  2017       3           27900.0     2.0      7900.0
153473  서울특별시 종로구 익선동 55  현대뜨레비앙     7      28.10              2017-02-01  2017       2           19900.0     1.0      9900.0
153474  서울특별시 종로구 익선동 55  현대뜨레비앙     3      46.64              2017-02-01  2017       2           26900.0     2.0      6900.0
153475  서울특별시 종로구 익선동 55  현대뜨레비앙     4      46.64              2017-02-01  2017       2           27000.0     2.0      7000.0
153476  서울특별시 종로구 익선동 55  현대뜨레비앙     6      48.54              2017-02-01  2017       2           29000.0     2.0      9000.0
158599  서울특별시 종로구 익선동 55  현대뜨레비앙     6      43.98              2017-01-01  2017       1           24000.0     2.0      4000.0
161732  서울특별시 종로구 익선동 55  현대뜨레비앙     5      48.54              2016-12-01  2016       12          28000.0     2.0      8000.0
161733  서울특별시 종로구 익선동 55  현대뜨레비앙     2      48.54              2016-12-01  2016       12          27000.0     2.0      7000.0
161734  서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2016-12-01  2016       12          25000.0     2.0      5000.0
165343  서울특별시 종로구 익선동 55  현대뜨레비앙     3      46.64              2016-11-01  2016       11          28000.0     2.0      8000.0
181611  서울특별시 종로구 익선동 55  현대뜨레비앙     5      46.64              2016-09-01  2016       9           26800.0     2.0      6800.0
181612  서울특별시 종로구 익선동 55  현대뜨레비앙     5      46.64              2016-09-01  2016       9           27300.0     2.0      7300.0
...                  ...     ...    ..        ...                     ...   ...      ..               ...     ...         ...
658331  서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2009-07-01  2009       7           16400.0     1.0      6400.0
658332  서울특별시 종로구 익선동 55  현대뜨레비앙     6      45.50              2009-07-01  2009       7           17000.0     1.0      7000.0
665853  서울특별시 종로구 익선동 55  현대뜨레비앙     9      45.50              2009-06-01  2009       6           21600.0     2.0      1600.0
665854  서울특별시 종로구 익선동 55  현대뜨레비앙     3      46.64              2009-06-01  2009       6           17000.0     1.0      7000.0
665855  서울특별시 종로구 익선동 55  현대뜨레비앙     2      48.54              2009-06-01  2009       6           18000.0     1.0      8000.0
665856  서울특별시 종로구 익선동 55  현대뜨레비앙     7      36.08              2009-06-01  2009       6           15500.0     1.0      5500.0
665857  서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2009-06-01  2009       6           17400.0     1.0      7400.0
665858  서울특별시 종로구 익선동 55  현대뜨레비앙     5      46.64              2009-06-01  2009       6           17500.0     1.0      7500.0
674201  서울특별시 종로구 익선동 55  현대뜨레비앙     2      48.54              2009-05-01  2009       5           17000.0     1.0      7000.0
674202  서울특별시 종로구 익선동 55  현대뜨레비앙     5      48.54              2009-05-01  2009       5           18000.0     1.0      8000.0
674203  서울특별시 종로구 익선동 55  현대뜨레비앙     9      39.90              2009-05-01  2009       5           18500.0     1.0      8500.0
674204  서울특별시 종로구 익선동 55  현대뜨레비앙     3      48.54              2009-05-01  2009       5           17500.0     1.0      7500.0
674205  서울특별시 종로구 익선동 55  현대뜨레비앙     5      48.54              2009-05-01  2009       5           19800.0     1.0      9800.0
680448  서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2009-04-01  2009       4           15000.0     1.0      5000.0
680449  서울특별시 종로구 익선동 55  현대뜨레비앙     6      48.54              2009-04-01  2009       4           18000.0     1.0      8000.0
680450  서울특별시 종로구 익선동 55  현대뜨레비앙     3      45.50              2009-04-01  2009       4           14500.0     1.0      4500.0
680451  서울특별시 종로구 익선동 55  현대뜨레비앙     2      48.54              2009-04-01  2009       4           17800.0     1.0      7800.0
688564  서울특별시 종로구 익선동 55  현대뜨레비앙     6      48.54              2009-03-01  2009       3           18000.0     1.0      8000.0
688565  서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2009-03-01  2009       3           15000.0     1.0      5000.0
688566  서울특별시 종로구 익선동 55  현대뜨레비앙     5      43.98              2009-03-01  2009       3           16200.0     1.0      6200.0
688567  서울특별시 종로구 익선동 55  현대뜨레비앙     6      43.98              2009-03-01  2009       3           15700.0     1.0      5700.0
688568  서울특별시 종로구 익선동 55  현대뜨레비앙     8      28.10              2009-03-01  2009       3           12900.0     1.0      2900.0
688569  서울특별시 종로구 익선동 55  현대뜨레비앙     9      48.54              2009-03-01  2009       3           21100.0     2.0      1100.0
693332  서울특별시 종로구 익선동 55  현대뜨레비앙     2      58.78              2009-02-01  2009       2           21000.0     2.0      1000.0
693333  서울특별시 종로구 익선동 55  현대뜨레비앙     6      43.98              2009-02-01  2009       2           16000.0     1.0      6000.0
693334  서울특별시 종로구 익선동 55  현대뜨레비앙     3      46.64              2009-02-01  2009       2           15800.0     1.0      5800.0
693335  서울특별시 종로구 익선동 55  현대뜨레비앙     2      46.64              2009-02-01  2009       2           15500.0     1.0      5500.0
693336  서울특별시 종로구 익선동 55  현대뜨레비앙     7      48.54              2009-02-01  2009       2           18600.0     1.0      8600.0
698034  서울특별시 종로구 익선동 55  현대뜨레비앙     5      46.64              2009-01-01  2009       1           17000.0     1.0      7000.0
698035  서울특별시 종로구 익선동 55  현대뜨레비앙     6      43.98              2009-01-01  2009       1           15900.0     1.0      5900.0

[200 rows x 10 columns]

In [35]:
recent_avr_price = search_list['deal_price'][(search_list['deal_year'] == 2018) & (12 - search_list['deal_month'] <= 6)]

In [36]:
if len(recent_avr_price) != 0:
    print(recent_avr_price.mean())

In [30]:
recent_avr_price

Series([], Name: deal_price, dtype: float64)

In [107]:
temp_list = [
 'full_addr',
 '법정동코드',
 'transaction_year_month',
 'year_of_completion',
 'exclusive_use_area',
 'floor',
 'latitude',
 'longitude',
 'total_parking_capacity_in_site',
 'total_household_count_in_sites',
 'apartment_building_count_in_sites',
 'tallest_building_in_sites',
 'lowest_building_in_sites',
 'heat_type',
 'heat_fuel',
 'supply_area',
 'room_count',
 'bathroom_count',
 'front_door_structure']

In [92]:
temp4 = temp3[temp_list]

# 건설사 순위 더하기

In [93]:
cons_df = pd.read_csv('output_v2.csv')

In [94]:
const_df = cons_df[['apt_jibun', 'cont_rank']]
const_df.head()

               apt_jibun  cont_rank
0  서울특별시 강남구 개포동 1164-14        NaN
1  서울특별시 강남구 개포동 1164-20     1689.0
2  서울특별시 강남구 개포동 1164-25        NaN
3  서울특별시 강남구 개포동 1164-28        NaN
4  서울특별시 강남구 개포동 1164-30        NaN

In [95]:
const_df = const_df.rename(columns = {'apt_jibun': 'full_addr'})

In [96]:
const_df['cont_rank'] = const_df['cont_rank'].fillna(1000)

In [97]:
const_df.head()

               full_addr  cont_rank
0  서울특별시 강남구 개포동 1164-14     1000.0
1  서울특별시 강남구 개포동 1164-20     1689.0
2  서울특별시 강남구 개포동 1164-25     1000.0
3  서울특별시 강남구 개포동 1164-28     1000.0
4  서울특별시 강남구 개포동 1164-30     1000.0

In [98]:
len(pd.unique(const_df['full_addr']))

7910

In [99]:
len(const_df)

7910

In [ ]:
# const_df.loc[const_df['full_addr'] == '서울특별시 강남구 역삼동 765-32']

In [ ]:
# total_df = pd.merge(temp, const_df, on="full_addr", how="inner")

In [ ]:
# temp = temp.drop('cont_rank', 1)

In [100]:
temp.shape

(973841, 52)

In [ ]:
len(temp.loc[temp['full_addr'] == '서울특별시 강남구 역삼동 765-32'])

In [ ]:
# total_df2 = temp.insert(10, 'cont_rank', temp['full_addr'].map(const_df.set_index('full_addr')['cont_rank']))

In [101]:
total_df = pd.merge(temp, const_df, how='inner', on = 'full_addr')

In [102]:
total_df.shape

(973812, 53)

In [103]:
total_df = total_df.drop_duplicates()

In [104]:
total_df.shape

(973812, 53)

In [ ]:
total_df.loc[total_df['full_address'] == '서울특별시 강남구 역삼동 765-32']

In [ ]:
# total_df2 = temp.join(const_df, lsuffix='_left', rsuffix='_right').set_index('full_addr')

In [ ]:
len(total_df.loc[total_df['full_address'] == '서울특별시 강남구 역삼동 765-32'])

In [ ]:
# total_df = pd.merge(temp, const_df, left_on="full_addr", right_on='apt_jibun', how="inner")

In [105]:
len(pd.unique(total_df['loc_code_x']))

25

In [106]:
total_df.tail()

,deal_price,deal_year,deal_month,full_loc_code,loc_code_x,gu_list,law_code,dong,ji_bun,apt_name_y,...,S-LineIC,S-LineAir,distance,full_address,price_yard,deal_date,full_addr,entirelawcode,yearmonth,cont_rank
973807,82000,2018,9,1117017,11170,용산구,이태원동,17,254-10,다원,...,NaN,NaN,463.0,서울특별시 용산구 이태원동 254-10,606.778156,2018-09-01,서울특별시 용산구 이태원동 254-10,서울특별시 용산구 이태원동,20189,1000.0
973808,22500,2018,9,1123005,11230,동대문구,장안동,05,344-2,다우하임,...,NaN,NaN,587.0,서울특별시 동대문구 장안동 344-2,750.500334,2018-09-01,서울특별시 동대문구 장안동 344-2,서울특별시 동대문구 장안동,20189,1000.0
973809,55000,2018,9,1153007,11530,구로구,오류동,07,352,천왕이펜하우스1단지,...,NaN,NaN,123.0,서울특별시 구로구 오류동 352,917.584251,2018-09-01,서울특별시 구로구 오류동 352,서울특별시 구로구 오류동,20189,142.0
973810,44500,2018,10,1162003,11620,관악구,신림동,03,244-21,래디앙,...,NaN,NaN,662.5,서울특별시 관악구 신림동 244-21,704.225352,2018-10-01,서울특별시 관악구 신림동 244-21,서울특별시 관악구 신림동,201810,1000.0
973811,50900,2018,10,1174007,11740,강동구,성내동,07,410-15,성내웰빙시티,...,NaN,NaN,624.0,서울특별시 강동구 성내동 410-15,853.597183,2018-10-01,서울특별시 강동구 성내동 410-15,서울특별시 강동구 성내동,201810,1000.0

# 디콘 합치기

In [ ]:
extra_df = pd.merge(temp, temp4, how='inner', on = 'full_addr')

### 데이터 바꾸기

In [ ]:
completed_years = total_df['completed_date']

In [ ]:
def get_year(date):
    if(date.find('.') != -1):
        return date.split('.')[0]
    else:
        return '-1'
    
def get_month(date):
    if(date.find('.') != -1):
        return date.split('.')[1]
    else:
        return '-1'

In [ ]:
total_df['com_year'] = completed_years.map(get_year)
total_df['com_mon'] = completed_years.map(get_month)

In [ ]:
total_df['avg_price'] = total_df['deal_price'] / total_df['area']

In [ ]:
total_df.shape

In [ ]:
total_df = total_df.drop(['full_addr', 'ji_bun', 'apt_name_y', 'gu_list', 'law_code', 'S-LineIC', 'apt_name_y', 'build_y'], 1)

In [ ]:
total_df = total_df.drop('full_loc_code', 1)

In [ ]:
total_df = total_df.drop('completed_date', 1)

In [ ]:
total_df = total_df.drop('full_address', 1)

In [ ]:
total_df = total_df.drop('price_yard', 1)

In [ ]:
subway_list = ['S-Line1',
 'S-Line2',
 'S-Line3',
 'S-Line4',
 'S-Line5',
 'S-Line6',
 'S-Line7',
 'S-Line8',
 'S-Line9',
 'S-LineBD',
 'S-LineNBD',
 'S-LineGC',
 'S-LineJA',
 'S-LineAir']

In [ ]:
total_df[subway_list] = total_df[subway_list].fillna(0)

In [ ]:
total_df['distance'] = total_df['distance'].fillna(0)

In [ ]:
to_int = ['current_floor', 'total_unit', 'total_building', 'max_floor', 'min_floor',
          'total_parking', 'unit_parking', 'conv_lists', 'medi_lists', 'park_lists', 'road_lists', 'kindergarten','elementary_school', 'middle_school',
 'high_school', 'university', 'etc_lists', 'S-Line1', 'S-Line2', 'S-Line3', 'S-Line4', 'S-Line5',
 'S-Line6', 'S-Line7', 'S-Line8', 'S-Line9', 'S-LineBD', 'S-LineNBD', 'S-LineGC', 'S-LineJA',
 'S-LineAir', 'distance','avg_price','cont_rank','com_year','com_mon','area', 'deal_year']

In [ ]:
total_df[['loc_code_x', 'dong']] = total_df[['loc_code_x', 'dong']].astype(int)

In [ ]:
total_df[to_int] = total_df[to_int].astype(int)

In [ ]:
total_df['sub_num'] = total_df['S-Line1'] + total_df['S-Line2'] + total_df['S-Line3'] + total_df['S-Line4'] + total_df['S-Line5'] + total_df['S-Line6'] + total_df['S-Line7'] + total_df['S-Line8'] + total_df['S-Line9'] + total_df['S-LineBD'] + total_df['S-LineNBD'] + total_df['S-LineGC'] + total_df['S-LineJA'] + total_df['S-LineAir']

In [ ]:
total_df.info()

In [ ]:
total_df['bldg_age'] = total_df['deal_year'] - total_df['com_year']

In [ ]:
total_df['lv_fg'] = total_df['current_floor'] / total_df['max_floor']

In [ ]:
total_df.isnull().sum()

In [ ]:
total_df.loc[total_df['com_year'] == -1]

In [ ]:
total_df = total_df.loc[total_df['com_year'] != -1]

In [ ]:
with open('final_total_data(1113)_final.txt', 'wb') as f:
    pickle.dump(total_df, f)

In [ ]:
len(pd.unique(total_df['loc_code_x']))

In [ ]:
total_df.shape

In [ ]:
total_df.info()

In [ ]:
de_etc = total_df.loc[total_df['loc_code_x'] == 11650]

In [ ]:
de_etc

In [ ]:
len(de_etc.loc[de_etc['cont_rank'] != 1000])

In [ ]:
de_etc.loc[de_etc['cont_rank'] != 1000]

### normalize를 하고 싶은걸요

In [ ]:
total_df

In [ ]:
total_df.loc[total_df['loc_code_x'] == 11110, 'loc_code_x'] = 1
total_df.loc[total_df['loc_code_x'] == 11140, 'loc_code_x'] = 2
total_df.loc[total_df['loc_code_x'] == 11170, 'loc_code_x'] = 3
total_df.loc[total_df['loc_code_x'] == 11200, 'loc_code_x'] = 4
total_df.loc[total_df['loc_code_x'] == 11215, 'loc_code_x'] = 5
total_df.loc[total_df['loc_code_x'] == 11230, 'loc_code_x'] = 6
total_df.loc[total_df['loc_code_x'] == 11260, 'loc_code_x'] = 7
total_df.loc[total_df['loc_code_x'] == 11290, 'loc_code_x'] = 8
total_df.loc[total_df['loc_code_x'] == 11305, 'loc_code_x'] = 9
total_df.loc[total_df['loc_code_x'] == 11320, 'loc_code_x'] = 10
total_df.loc[total_df['loc_code_x'] == 11350, 'loc_code_x'] = 11
total_df.loc[total_df['loc_code_x'] == 11380, 'loc_code_x'] = 12
total_df.loc[total_df['loc_code_x'] == 11410, 'loc_code_x'] = 13
total_df.loc[total_df['loc_code_x'] == 11440, 'loc_code_x'] = 14
total_df.loc[total_df['loc_code_x'] == 11470, 'loc_code_x'] = 15
total_df.loc[total_df['loc_code_x'] == 11500, 'loc_code_x'] = 16
total_df.loc[total_df['loc_code_x'] == 11530, 'loc_code_x'] = 17
total_df.loc[total_df['loc_code_x'] == 11545, 'loc_code_x'] = 18
total_df.loc[total_df['loc_code_x'] == 11560, 'loc_code_x'] = 19
total_df.loc[total_df['loc_code_x'] == 11590, 'loc_code_x'] = 20
total_df.loc[total_df['loc_code_x'] == 11620, 'loc_code_x'] = 21
total_df.loc[total_df['loc_code_x'] == 11650, 'loc_code_x'] = 22
total_df.loc[total_df['loc_code_x'] == 11680, 'loc_code_x'] = 23
total_df.loc[total_df['loc_code_x'] == 11710, 'loc_code_x'] = 24
total_df.loc[total_df['loc_code_x'] == 11740, 'loc_code_x'] = 25

In [ ]:
#normalization
from sklearn import preprocessing
import numpy as np

In [ ]:
def add_nor(total_df, nor_list):
    for i in nor_list:
        data_array = np.array(total_df[i])
        nor_data = preprocessing.normalize([data_array])
        nor_data = nor_data.reshape(-1, 1)
        total_df["nml_" + i] = pd.DataFrame(nor_data)

In [ ]:
add_nor(total_df, ['deal_price'])

In [ ]:
total_df = total_df.drop('nml_deal_price', 1)

In [ ]:
total_df.isnull().sum()

In [ ]:
with open('final_total_data2(1113).txt', 'wb') as f:
    pickle.dump(total_df, f)

### Let's explore data

In [ ]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from scipy import stats
%matplotlib inline

In [ ]:
total_df['loc_code_x'].value_counts().plot(kind='bar')
plt.title('No. of house per each district')
plt.xlabel('House')
plt.ylabel('Count')
sns.despine

In [ ]:
df_2018 = total_df.loc[total_df['deal_year'] == 2018]
df_2017 = total_df.loc[total_df['deal_year'] == 2017]
df_2016 = total_df.loc[total_df['deal_year'] == 2016]
df_2015 = total_df.loc[total_df['deal_year'] == 2015]
df_2014 = total_df.loc[total_df['deal_year'] == 2014]
df_2013 = total_df.loc[total_df['deal_year'] == 2013]
df_2012 = total_df.loc[total_df['deal_year'] == 2012]
df_2011 = total_df.loc[total_df['deal_year'] == 2011]
df_2010 = total_df.loc[total_df['deal_year'] == 2010]
df_2009 = total_df.loc[total_df['deal_year'] == 2009]
df_2008 = total_df.loc[total_df['deal_year'] == 2008]
df_2007 = total_df.loc[total_df['deal_year'] == 2007]
df_2006 = total_df.loc[total_df['deal_year'] == 2006]

In [ ]:
avgprice_2018 = df_2018['avg_price']
avgprice_2017 = df_2017['avg_price']
avgprice_2016 = df_2016['avg_price']
avgprice_2015 = df_2015['avg_price']
avgprice_2014 = df_2014['avg_price']
avgprice_2013 = df_2013['avg_price']
avgprice_2012 = df_2012['avg_price']
avgprice_2011 = df_2011['avg_price']
avgprice_2010 = df_2010['avg_price']
avgprice_2009 = df_2009['avg_price']
avgprice_2008 = df_2008['avg_price']
avgprice_2007 = df_2007['avg_price']
avgprice_2006 = df_2006['avg_price']

In [ ]:
total_df = total_df.drop('gu_name', 1)

In [ ]:
jongro_df = total_df.loc[total_df['loc_code_x'] == 1]
jung_df = total_df.loc[total_df['loc_code_x'] == 2]
yongsan_df = total_df.loc[total_df['loc_code_x'] == 3]
sungdong_df = total_df.loc[total_df['loc_code_x'] == 4]
kwangjin_df = total_df.loc[total_df['loc_code_x'] == 5]
dongdaemun_df = total_df.loc[total_df['loc_code_x'] == 6]
jungrang_df = total_df.loc[total_df['loc_code_x'] == 7]
sungbuk_df = total_df.loc[total_df['loc_code_x'] == 8]
gangbuk_df = total_df.loc[total_df['loc_code_x'] == 9]
dobong_df = total_df.loc[total_df['loc_code_x'] == 10]
nohwon_df = total_df.loc[total_df['loc_code_x'] == 11]
eunpyeong_df = total_df.loc[total_df['loc_code_x'] == 12]
seodaemun_df = total_df.loc[total_df['loc_code_x'] == 13]
mapo_df = total_df.loc[total_df['loc_code_x'] == 14]
yangcheon_df = total_df.loc[total_df['loc_code_x'] == 15]
gangsuh_df = total_df.loc[total_df['loc_code_x'] == 16]
guro_df = total_df.loc[total_df['loc_code_x'] == 17]
keumcheon_df = total_df.loc[total_df['loc_code_x'] == 18]
youngdeungpo_df = total_df.loc[total_df['loc_code_x'] == 19]
dongjak_df = total_df.loc[total_df['loc_code_x'] == 20]
kwanak_df = total_df.loc[total_df['loc_code_x'] == 21]
seocho_df = total_df.loc[total_df['loc_code_x'] == 22]
gangnam_df = total_df.loc[total_df['loc_code_x'] == 23]
songpa_df = total_df.loc[total_df['loc_code_x'] == 24]
gangdong_df = total_df.loc[total_df['loc_code_x'] == 25]

In [ ]:
jongro_avgprice = jongro_df['avg_price']
jung_avgprice = jung_df['avg_price']
yongsan_avgprice = yongsan_df['avg_price']
sungdong_avgprice = sungdong_df['avg_price']
kwangjin_avgprice = kwangjin_df['avg_price']
dongdaemun_avgprice = dongdaemun_df['avg_price']
jungrang_avgprice = jungrang_df['avg_price']
sungbuk_avgprice = sungbuk_df['avg_price']
gangbuk_avgprice = gangbuk_df['avg_price']
dobong_avgprice = dobong_df['avg_price']
nohwon_avgprice = nohwon_df['avg_price']
eunpyeong_avgprice = eunpyeong_df['avg_price']
seodaemun_avgprice = seodaemun_df['avg_price']
mapo_avgprice = mapo_df['avg_price']
yangcheon_avgprice = yangcheon_df['avg_price']
gangsuh_avgprice = gangsuh_df['avg_price']
guro_avgprice = guro_df['avg_price']
keumcheon_avgprice = keumcheon_df['avg_price']
youngdeungpo_avgprice = youngdeungpo_df['avg_price']
dongjak_avgprice = dongjak_df['avg_price']
kwanak_avgprice = kwanak_df['avg_price']
seocho_avgprice = seocho_df['avg_price']
gangnam_avgprice = gangnam_df['avg_price']
songpa_avgprice = songpa_df['avg_price']
gangdong_avgprice = gangdong_df['avg_price']

In [ ]:
sns.set(color_codes=True)

In [ ]:
sns.distplot(jongro_avgprice)
sns.distplot(jung_avgprice)
sns.distplot(yongsan_avgprice)
sns.distplot(sungdong_avgprice)
sns.distplot(kwangjin_avgprice)
sns.distplot(dongdaemun_avgprice)
sns.distplot(jungrang_avgprice)
sns.distplot(sungbuk_avgprice)
sns.distplot(gangbuk_avgprice)
sns.distplot(dobong_avgprice)
sns.distplot(nohwon_avgprice)
sns.distplot(eunpyeong_avgprice)
sns.distplot(seodaemun_avgprice)
sns.distplot(mapo_avgprice)
sns.distplot(yangcheon_avgprice)
sns.distplot(gangsuh_avgprice)
sns.distplot(guro_avgprice)
sns.distplot(keumcheon_avgprice)
sns.distplot(youngdeungpo_avgprice)
sns.distplot(dongjak_avgprice)
sns.distplot(kwanak_avgprice)
sns.distplot(seocho_avgprice)
sns.distplot(gangnam_avgprice)
sns.distplot(songpa_avgprice)
sns.distplot(gangdong_avgprice)

In [ ]:
sns.distplot(avgprice_2018)
sns.distplot(avgprice_2017)
sns.distplot(avgprice_2016)
sns.distplot(avgprice_2015)
sns.distplot(avgprice_2014)
sns.distplot(avgprice_2013)
sns.distplot(avgprice_2012)
sns.distplot(avgprice_2011)
sns.distplot(avgprice_2010)
sns.distplot(avgprice_2009)
sns.distplot(avgprice_2008)
sns.distplot(avgprice_2007)
sns.distplot(avgprice_2006)

### scatterplot

In [ ]:
area_dic = {'jongro': 1, 'jung':2, 'yongsan':3, 'sungdong':4, 'kwangjin':5, 'dongdaemun':6, 'jungrang':7, 'sungbuk':8, 
            'gangbuk' : 9, 'dobong':10, 'nohwon':11, 'eunpyeong':12, 'seodaemun':13, 'mapo':14, 'yangcheon':15, 'gangsuh':16, 
            'guro':17, 'keumcheon':18, 'youngdeungpo':19, 'dongjak':20, 'kwanak':21, 'seocho':22, 'gangnam':23, 'songpa':24, 'gangdong':25}

In [ ]:
areako_dic = {'종로구': 1, '중구':2, '용산구':3, '성동구':4, '광진구':5, '동대문구':6, '중랑구':7, '성북구':8, 
            '강북구' : 9, '도봉구':10, '노원구':11, '은평구':12, '서대문구':13, '마포구':14, '양천구':15, '강서구':16, 
            '구로구':17, '금천구':18, '영등포구':19, '동작구':20, '관악구':21, '서초구':22, '강남구':23, '송파구':24, '강동구':25}

In [ ]:
areakor_dic = {v: k for k, v in areako_dic.items()}

In [ ]:
areakor_dic

In [ ]:
total_df['gu_name'] = np.nan

In [ ]:
total_df['gu_name'] = total_df['loc_code_x'].map(areakor_dic)

In [ ]:
# gangnam = merged_total.loc[:][merged_total['loc_code_x']=='11680']
# gn_2017 = gangnam.loc[gangnam.deal_year == 2017]
plt.figure(figsize=(8,6), dpi=80)
plt.scatter(total_df['avg_price'],total_df['deal_year'], s=5)

In [ ]:
plt.figure(figsize=(8,6), dpi=80)
plt.scatter(total_df['avg_price'],total_df['gu_name'], s=5)
# plt.subplots_adjust(bottom = 0.00001)

In [ ]:
total_df['gu_name'].value_counts().plot(kind='bar')
plt.title('No. of house per each district')
plt.xlabel('House')
plt.ylabel('Count')

In [ ]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.font_manager as fm

In [ ]:
font_location = '/Library/Fonts/NanumBarunGothicOTF-YetHangul.otf'
font_name = fm.FontProperties(fname=font_location).get_name()
print(font_name)
fm.FontProperties(fname=font_location)
mpl.rc('font', family=font_name)

In [ ]:
sns.distplot(avgprice_2018, kde=False, fit=stats.gamma)
print(avgprice_2018.mean())
print(avgprice_2018.std())

In [ ]:
# sns.distplot(avgprice_2017, kde=False, fit=stats.gamma)
sns.distplot(avgprice_2017, kde=False)
print(avgprice_2017.mean())
print(avgprice_2017.std())

In [ ]:
# sns.distplot(avgprice_2016, kde=False, fit=stats.gamma)
sns.distplot(avgprice_2016, kde=False)
print(avgprice_2016.mean())
print(avgprice_2016.std())

In [ ]:
sns.distplot(avgprice_2015, kde=False)
print(avgprice_2015.mean())
print(avgprice_2015.std())

In [ ]:
sns.distplot(avgprice_2014, kde=False)
print(avgprice_2014.mean())
print(avgprice_2014.std())

In [ ]:
sns.distplot(avgprice_2013, kde=False)
print(avgprice_2013.mean())
print(avgprice_2013.std())

In [ ]:
sns.distplot(avgprice_2012, kde=False)
print(avgprice_2012.mean())
print(avgprice_2012.std())

In [ ]:
sns.distplot(avgprice_2011, kde=False)
print(avgprice_2011.mean())
print(avgprice_2011.std())

In [ ]:
sns.distplot(avgprice_2010, kde=False)
print(avgprice_2010.mean())
print(avgprice_2010.std())

In [ ]:
sns.distplot(avgprice_2009, kde=False)
print(avgprice_2009.mean())
print(avgprice_2009.std())

In [ ]:
sns.distplot(avgprice_2008, kde=False)
print(avgprice_2008.mean())
print(avgprice_2008.std())

In [ ]:
sns.distplot(avgprice_2007, kde=False)
print(avgprice_2007.mean())
print(avgprice_2007.std())

In [ ]:
sns.distplot(avgprice_2006, kde=False)
print(avgprice_2006.mean())
print(avgprice_2006.std())

### 지역별

In [ ]:
sns.distplot(jongro_avgprice, kde=False, fit=stats.gamma)
print(jongro_avgprice.mean())
print(jongro_avgprice.std())

In [ ]:
sns.distplot(jung_avgprice, kde=False, fit=stats.gamma)
print(jung_avgprice.mean())
print(jung_avgprice.std())

In [ ]:
sns.distplot(yongsan_avgprice, kde=False, fit=stats.gamma)
print(yongsan_avgprice.mean())
print(yongsan_avgprice.std())

In [ ]:
sns.distplot(sungdong_avgprice, kde=False, fit=stats.gamma)
print(sungdong_avgprice.mean())
print(sungdong_avgprice.std())

In [ ]:
sns.distplot(kwangjin_avgprice, kde=False, fit=stats.gamma)
print(kwangjin_avgprice.mean())
print(kwangjin_avgprice.std())

In [ ]:
sns.distplot(dongdaemun_avgprice, kde=False, fit=stats.gamma)
print(dongdaemun_avgprice.mean())
print(dongdaemun_avgprice.std())

In [ ]:
sns.distplot(jungrang_avgprice, kde=False, fit=stats.gamma)
print(jungrang_avgprice.mean())
print(jungrang_avgprice.std())

In [ ]:
sns.distplot(sungbuk_avgprice, kde=False, fit=stats.gamma)
print(sungbuk_avgprice.mean())
print(sungbuk_avgprice.std())

In [ ]:
sns.distplot(gangbuk_avgprice, kde=False, fit=stats.gamma)
print(gangbuk_avgprice.mean())
print(gangbuk_avgprice.std())

In [ ]:
sns.distplot(dobong_avgprice, kde=False, fit=stats.gamma)
print(dobong_avgprice.mean())
print(dobong_avgprice.std())

In [ ]:
sns.distplot(nohwon_avgprice, kde=False, fit=stats.gamma)
print(nohwon_avgprice.mean())
print(nohwon_avgprice.std())

In [ ]:
sns.distplot(eunpyeong_avgprice, kde=False, fit=stats.gamma)
print(eunpyeong_avgprice.mean())
print(eunpyeong_avgprice.std())

In [ ]:
sns.distplot(seodaemun_avgprice, kde=False, fit=stats.gamma)
print(seodaemun_avgprice.mean())
print(seodaemun_avgprice.std())

In [ ]:
sns.distplot(mapo_avgprice, kde=False, fit=stats.gamma)
print(mapo_avgprice.mean())
print(mapo_avgprice.std())

In [ ]:
sns.distplot(yangcheon_avgprice, kde=False, fit=stats.gamma)
print(yangcheon_avgprice.mean())
print(yangcheon_avgprice.std())

In [ ]:
sns.distplot(gangsuh_avgprice, kde=False, fit=stats.gamma)
print(gangsuh_avgprice.mean())
print(gangsuh_avgprice.std())

In [ ]:
sns.distplot(guro_avgprice, kde=False, fit=stats.gamma)
print(guro_avgprice.mean())
print(guro_avgprice.std())

In [ ]:
sns.distplot(keumcheon_avgprice, kde=False, fit=stats.gamma)
print(keumcheon_avgprice.mean())
print(keumcheon_avgprice.std())

In [ ]:
sns.distplot(youngdeungpo_avgprice, kde=False, fit=stats.gamma)
print(youngdeungpo_avgprice.mean())
print(youngdeungpo_avgprice.std())

In [ ]:
sns.distplot(dongjak_avgprice, kde=False, fit=stats.gamma)
print(dongjak_avgprice.mean())
print(dongjak_avgprice.std())

In [ ]:
sns.distplot(kwanak_avgprice, kde=False, fit=stats.gamma)
print(kwanak_avgprice.mean())
print(kwanak_avgprice.std())

In [ ]:
sns.distplot(seocho_avgprice, kde=False, fit=stats.gamma)
print(seocho_avgprice.mean())
print(seocho_avgprice.std())

In [ ]:
sns.distplot(gangnam_avgprice, kde=False, fit=stats.gamma)
print(gangnam_avgprice.mean())
print(gangnam_avgprice.std())

In [ ]:
sns.distplot(songpa_avgprice, kde=False, fit=stats.gamma)
print(songpa_avgprice.mean())
print(songpa_avgprice.std())

In [ ]:
sns.distplot(gangdong_avgprice, kde=False, fit=stats.gamma)
print(gangdong_avgprice.mean())
print(gangdong_avgprice.std())

### 클러스터링

In [ ]:
# data = total_df.drop('gu_name', 1).values
data = total_df.values

In [ ]:
import numpy as np
from sklearn.cluster import KMeans
from sklearn import metrics

In [ ]:
kmeans_model = KMeans(n_clusters = 4, random_state=1).fit(data)

In [ ]:
labels = kmeans_model.labels_

In [ ]:
# metrics.silhouette_score(data, labels, metric='euclidean')

In [ ]:
km_results = pd.DataFrame([labels]).T

In [ ]:
km_result = km_results.join(total_df['gu_name'])

In [ ]:
km_result.columns = ['cluster', 'location']

In [ ]:
km_result.head()

In [ ]:
total_df.isnull().sum()

In [ ]:
# km_result.dropna(subset=['location'], how='all', inplace = True)

In [ ]:
figure = plt.figure(figsize=(15,8))
plt.hist([km_result[km_result['cluster']==0]['location'], km_result[km_result['cluster']==1]['location'], 
          km_result[km_result['cluster']==2]['location'], km_result[km_result['cluster']==3]['location']], 
          stacked=True, bins=30, label=['Cluster 1','Cluster 2', 'Cluster 3', 'Cluster 4'])
plt.xlabel('Location')
plt.ylabel('Clusters')
plt.legend()

### 아웃라이어 제거

In [ ]:
#standardization
from scipy import stats
import numpy as np

In [ ]:
def standardization(data, threshold):
    z = np.abs(stats.zscore(data))
    return np.where(z>threshold)

In [ ]:
outliers_seocho = standardization(total_df.loc[total_df['loc_code_x'] == 22]['avg_price'], 2)

In [ ]:
outliers_seocho

In [ ]:
new_df2 = total_df.drop(outliers_seocho[0])

In [ ]:
outliers_sp = standardization(total_df.loc[total_df['loc_code_x'] == 24]['avg_price'], 3)

In [ ]:
outliers_sp

In [ ]:
new_df = new_df.drop([  166,   172,   181,   190,   192,   199,   201,   204,   207,
          211,   212,   215,   219,   220,   223,   226,   228,   229,
         1575,  1579,  1581,  1582,  1589,  1593,  1594,  1595,  1597,
         1598,  1599,  1600,  1601,  1603,  1604,  1605,  1606,  1607,
         1608,  1609,  1610,  1611,  1612,  1632,  1634,  1635,  1636,
         1637,  1638,  1639,  1640,  1641,  1642,  1643,  1644,  1645,
         1646,  1647,  1648,  1651,  1652,  1653,  1654,  1655,  1656,
         1657,  1658,  1659,  1660,  1661,  1662,  1663,  1664,  1665,
         1666,  1667,  1668,  1669,  1670,  1671,  1673,  1674,  1675,
         1676,  1677,  1679,  1680,  1682,  1683,  1684,  1685,
         1686,  1687,  1688,  1689,  1690,  1691,  1692,  1693,  1694,
         1695,  1696,  1697,  1698,  1699,  1700,  1701,  1702,  1703,
         1704,  1705,  1706,  1707,  1708,  1709,  1710,  1711,  1712,
         1715,  1716,  1717,  1718,  1719,  1720,  1721,  1722,
         1723,  1724,  1725,  1726,  1727,  1728,  1729,  1730,  1731,
         1732,  1733,  1734,  1735,  1736,  1737,  1738,  1739,  1740,
         1741,  1742,  1743,  1744,  1745,  1746,  1747,  1748,  1749,
         1752,  1753,  1755,  1756,  1757,  1759,  1760,  1761,  1762,
         1763,  1764,  1765,  1766,  1767,  1768,  1769,  1770,  1771,
         1772,  1773,  1774,  1775,  1776,  1777,  1778,  1779,  1780,
         1781,  1782,  1783,  1784,  1785,  1786,  1787,  1788,  1789,
         1790,  1791,  1792,  1793,  1794,  1795,  1796,  1797,  1798,
         1799,  1800,  1801,  1802,  1803,  1804,  1805,  1806,  1807,
         1808,  1809,  1810,  1811,  1812,  1813,  1814,  1815,  1816,
         1817,  1818,  1819,  1821,  1822,  1823,  1824,  1825,  1826,
         1827,  1828,  1829,  1830,  1831,  1832,  1833,  1834,  1835,
         1836,  1837,  1838,  1839,  1840,  1841,  1842,  1843,  1844,
         1845,  1846,  1847,  1849,  1850,  1851,  1852,  1853,  1854,
         1855,  1856,  1857,  1858,  1859,  1860,  1861,  1862,  1863,
         1864,  1865,  1866,  1867,  1868,  1869,  1870,  1871,  1872,
         1873,  1874,  1875,  1876,  1877,  1878,  1879,  1880,  1881,
         1882,  1883,  1884,  1885,  1886,  1887,  1888,  1889,  1890,
         1891,  1892,  1893,  1894,  1895,  1896,  1897,  1898,  1899,
         1900,  1901,  1902,  1903,  1904,  1905,  1906,  1907,  1908,
         1909,  1910,  1911,  1912,  1913,  1914,  1915,  1916,  1917,
         1918,  1919,  1920,  1921,  1922,  1923,  1924,  1925,  1926,
         1927,  1928,  1929,  1930,  1931,  1932,  1933,  1934,  1935,
         1936,  1937,  1938,  1939,  1940,  1941,  1942,  1943,  1944,
         1945,  1946,  1947,  1948,  1949,  1950,  1951,  3580,  3581,
         3586,  3588,  3590,  3591,  3593,  3596,  3597,  3598,  3599,
         4821,  4822,  4823,  4824,  4827,  4828,  4829,  4830,  4832,
         4833,  5156,  5157,  6282,  6283,  6284,  6285,  6286,  6287,
         6288,  6289,  6290,  6291,  6292,  6293,  6294,  6295,  6296,
         6297,  6298,  6299,  6300,  6301,  6302,  6303,  6304,  6305,
         6306,  6307,  6310,  6311,  6312,  6313,  6316,  6317,  6318,
         6319,  6320,  6321,  7784,  7785,  8907,  8908,  8909, 30978,
        31026, 45112, 46397, 46416, 46420, 46422, 46424, 46444, 46445,
        46447, 46451, 46452, 46455, 46461, 46465, 46467, 46470, 46472,
        46474, 48499, 48519, 48526, 48532, 48540, 48542, 48549, 48551,
        48555, 48558, 48559, 48577, 48583, 48585, 48590, 48591, 48594,
        48595, 48601, 48604, 48605, 48610, 48614, 48615, 48618, 48622,
        48626, 48629, 48630, 48631, 48634, 48635, 48636, 48637, 48638,
        48639, 48640, 48641, 48644, 48645, 51562, 51608, 51624, 51631,
        51642, 51650, 51653, 51669, 51732, 51742, 51756, 51779, 51809,
        51813, 51817, 51847, 51851, 51853, 51857, 51860, 51868, 51902,
        51910, 51926, 51931, 51954, 51984, 52012, 52013, 52019, 52024,
        52035, 52036, 52037, 52038, 52042, 52044, 52061, 52074, 52084,
        52085, 52107, 52108, 52114, 52122, 52124, 52134, 52138, 52139,
        52140, 52144, 52145, 52149, 52150, 52152, 52154, 52156, 52171,
        52176, 52178, 52180, 52181, 52184, 52186, 52191, 52198, 52204,
        52208, 52214, 52233, 52255, 52267, 52270, 52278, 52280, 52281,
        52284, 52297, 52314, 52316, 52317, 52319, 52320, 52321, 52324,
        52325, 52327, 52335, 52340, 52348, 52352, 52356, 52364, 52370,
        52371, 52373, 52374, 52376, 52380, 52381, 52382, 52383, 52387,
        52390, 52392, 52403, 52413, 52419, 52423, 52426, 52427, 52435,
        52439, 52443, 52445, 52447, 52450, 52451, 52452, 52453,
        52454, 52455, 52456, 52458, 52459, 52460, 52461, 52463, 52464,
        52465, 52467, 52469, 52470, 52471, 52472, 52473, 52475, 52476,
        52477, 52478, 52480, 52482, 52484, 52485, 52486, 52487, 52488,
        52489, 52490, 52492, 52493, 52494, 52495, 52496, 52497, 52498,
        52499, 52500, 52501, 52503, 52504, 52505, 52508, 52509, 52512,
        52514, 52524, 52527, 52528, 52529, 52531, 52532, 52535, 52537,
        52538, 52540, 52541, 52542, 52543, 52545, 52546, 52547, 52548,
        52550, 52551, 52553, 52554, 52555, 52556, 52557, 52558, 52559,
        52560, 52562, 52563, 52564, 52565, 52566, 52567, 52568, 52569,
        52570, 52571, 52572, 52573, 52575, 52576, 52577, 52578, 52581,
        52582, 52584, 52585, 52586, 52587, 52588, 52589, 52590, 52591,
        52592, 52593, 52594, 52595, 52596, 52597, 52598, 52599, 52600,
        52601, 52602, 52603, 52604, 52605, 56680, 56735, 56736, 56738,
        56750, 56753, 56764, 56771, 56774, 56792, 56794, 56795, 56802,
        56803, 56805, 56807, 56811, 56816, 56818, 56825, 56832, 56836,
        56841, 56844, 56847, 56854, 56856, 56861, 56870, 56874, 56881,
        56882, 56883, 56886, 56892, 56894, 56896, 56897, 56901, 56902,
        56906, 56908, 56909, 56910, 56911, 59101, 59104, 59117, 59122,
        59123, 59124, 59131, 59142, 59145, 59147, 59148,
        59152, 59157, 59158, 59159, 59162, 59164, 59183, 59187, 59193,
        59195, 59200, 59202, 59203, 59205, 59207, 59215, 59218, 59221,
        59223, 59224, 59225, 59226, 59228, 59229, 59231, 59232, 59233,
        59234, 59235, 59236, 59237, 59239, 59240, 59241, 59242, 59244,
        59245, 59246, 59247, 59249, 59250, 59251, 59252, 59253, 59254,
        59255, 59256, 59258, 59261, 59262, 59263, 59264, 59265, 59267,
        59268, 59269, 59274, 59275, 59276, 59277, 59278, 59282, 59283,
        59289, 59290, 59292, 59294, 59295, 59298, 59301, 59306, 59309,
        59311, 59312, 59314, 59316, 59317, 59318, 59319, 59320, 59321,
        59322, 59323, 59324, 59325, 59326, 59327, 59328, 59329, 59330,
        59331, 59332, 59334, 59335, 59336, 59337, 59338, 59339, 59340,
        59341, 59342, 59343, 59344, 59345, 59346, 59347, 59348, 59350,
        59351, 59352, 59353, 59354, 59355, 59357, 59358, 59359, 59360,
        59361, 59362, 62123, 62124, 62133, 62139, 62142, 62145, 62146,
        62150, 62151])

In [ ]:
outliers_gn = standardization(total_df.loc[total_df['loc_code_x'] == 23]['avg_price'], 3)

In [ ]:
outliers_gn

In [ ]:
new_df = new_df.drop([  669,   672,   693,   694,   695,  1438,  1440,  2743,
         3917,  3923,  3924,  3925,  3932,  3934,  3935,  3941,  3945,
         3946,  3950,  3955,  3959,  3964,  3965,  3968,  3970,  3972,
         3974,  3976,  4012,  4014,  4021,  4025,  4034,  4037,  4041,
         4046,  4052,  4054,  4061,  4065,  4066,  4068,  4084,
         4085,  4087,  4090,  4091,  4092,  4094,  4095,  4097,  4098,
         4099,  4100,  4101,  4103,  4104,  4105,  4106,  4107,
         4109,  4110,  4112,  4113,  4114,  4115,  4116,  4117,  4118,
         4120,  4122,  4123,  4124,  4125,  4126,  4127,  4128,  4129,
         4130,  4132,  4133,  4134,  4138,  4139,  4141,  4142,  4143,
         4144,  4145,  4146,  4148,  4149,  4150,  4151,  4152,  4153,
         4154,  4155,  4156,  4157,  4158,  4159,  4160,  4161,  4162,
         4163,  4164,  4165,  4166,  4167,  4168,  4169,  4170,  4171,
         4172,  4173,  4174,  4175,  4176,  4177,  4178,  4179,  4180,
         4181,  4182,  5248,  5252,  5255,  5256,  5270,  5272,  5281,
         5285,  5286,  5289,  5296,  5297,  5298,  5299,  5300,  5301,
         9577,  9578,  9663,  9664,  9669,  9670,  9683,  9684,  9697,
         9698,  9701,  9702,  9711,  9712,  9713,  9714,  9719,  9720,
         9721,  9722,  9723,  9724,  9725,  9726,  9727,  9728,  9729,
         9730,  9731,  9732,  9733,  9734,  9735,  9736,  9737,  9738,
         9739,  9740,  9741,  9742, 11705, 11706, 11713, 11714, 11721,
        11722, 11729, 11730, 11743, 11744, 11749, 11750, 11791, 11792,
        11793, 11794, 11795, 11796, 11797, 11798, 11799, 11800, 12392,
        12396, 12397, 15636, 19813, 19814, 19821, 19822, 19863, 19864,
        19871, 19872, 19879, 19880, 20185, 20187, 20189, 20190, 20191,
        20192, 20193, 22474, 22483, 22484, 22485, 22486, 22487, 22488,
        22489, 23366, 23373, 23376, 23377, 23739, 23743, 25588, 25589,
        25594, 25595, 25598, 25599, 25604, 25605, 25616, 25617, 29340,
        29341, 29342, 29841, 29846, 29848, 29851, 29853, 29855, 29861,
        29862, 29863, 29866, 29867, 29868, 29869, 29870, 29871, 29872,
        29873, 29874, 29875, 29876, 29877, 29879, 29880, 29881, 29882,
        29883, 29884, 29885, 29886, 29887, 29888, 29889, 29890, 29891,
        29892, 29893, 29894, 29895, 29896, 29897, 29898, 29899, 29900,
        29901, 30074, 30081, 30083, 30084, 30085, 30087, 30088, 30089,
        30090, 30091, 30092, 30093, 30094, 30145, 30146, 30147, 30148,
        30149, 30150, 30151, 30152, 30153, 30154, 30525, 31469, 31470,
        31471, 31472, 31473, 31475, 31476, 31477, 31692, 31934, 32240,
        32356, 32359, 32360, 32361, 32362, 32363, 32364, 32365, 32366,
        32367, 32368, 36807, 36808, 36810, 36812, 40079, 40082, 43305,
        49666, 49667, 49707, 49727, 49730, 49737, 49738, 49739, 49740,
        49745, 49748, 51799, 51815, 51838, 51878, 51909, 51945, 51968,
        51974, 51975, 51977, 51987, 51995, 51997, 52000, 52001, 52002,
        52003, 52377, 54000, 54304, 54305, 54308, 54311, 54312, 54314,
        54315, 57754, 57755, 57758, 57763, 57778, 58149, 58152, 58154,
        58157, 58158, 58161, 58163, 58575, 58577, 58581, 58583, 58584,
        58591, 58592, 58595, 58596, 58600, 58601, 58604, 58606, 58608,
        58609, 58610, 58613, 58617, 58618, 58620, 58621, 58626, 58628,
        58684, 58946, 58948, 58949, 59685, 59881, 59886,
        59887, 59893, 59894, 59899, 59900, 59901, 59902, 59903, 59906,
        59908, 59910, 59911, 59912, 59914, 59915, 59916, 59917, 59918,
        59919, 59922, 59923, 59924, 59925, 59926, 59927, 59928, 59929,
        59930, 59931, 59932, 59933, 59934, 59935, 59936, 59937, 59938,
        59939, 59940, 59941, 60240, 60241, 61545, 61552, 61553, 61554,
        61563, 61564, 61567, 61572, 61575, 61576, 61578, 61580, 61581,
        61582, 61584, 61585, 61586, 61587, 61589, 61590, 61591, 61592,
        61593, 61595, 61596, 61597, 61598, 61599, 61600, 61601, 61602,
        61603, 61604, 61605, 61606, 61608, 61609, 61610, 61611, 61612,
        61613, 61614, 61615, 61875, 61876, 61878, 61909, 61911, 61912,
        61913])

In [ ]:
seocho_df2 = new_df.loc[new_df['loc_code_x'] == 22]
gangnam_df2 = new_df.loc[new_df['loc_code_x'] == 23]
songpa_df2 = new_df.loc[new_df['loc_code_x'] == 24]

In [ ]:
seocho_avgprice2 = seocho_df2['avg_price']
gangnam_avgprice2 = gangnam_df2['avg_price']
songpa_avgprice2 = songpa_df2['avg_price']

In [ ]:
sns.distplot(seocho_avgprice2, kde=False, fit=stats.gamma)
print(seocho_avgprice2.mean())
print(seocho_avgprice2.std())

In [ ]:
sns.distplot(gangnam_avgprice2, kde=False, fit=stats.gamma)
print(gangnam_avgprice2.mean())
print(gangnam_avgprice2.std())

In [ ]:
plt.figure(figsize=(8,6), dpi=80)
plt.scatter(new_df['avg_price'],new_df['loc_code_x'], s=5)
# plt.subplots_adjust(bottom = 0.00001)